
copy d:\amiga\text\winuaechangelog.txt c:\projects\winuae\src\od-win32
copy d:\amiga\text\winuaechangelog.txt c:\projects\winuae\distribution\docs

"C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" -d"DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\\" -dSolutionDir=C:\projects\winuae\src\od-win32\winuae_msvc15\ -dSolutionExt=.sln -dSolutionFileName=winuae_msvc.sln -dSolutionName=winuae_msvc -dSolutionPath=C:\projects\winuae\src\od-win32\winuae_msvc15\winuae_msvc.sln -dConfiguration=Release -dOutDir=bin\Release\ -dPlatform=x86 -dProjectDir=C:\projects\winuae\src\od-win32\wix\ -dProjectExt=.wixproj -dProjectFileName=wix.wixproj -dProjectName=wix -dProjectPath=C:\projects\winuae\src\od-win32\wix\wix.wixproj -dTargetDir=C:\projects\winuae\src\od-win32\wix\bin\Release\ -dTargetExt=.msi -dTargetFileName=winuae.msi -dTargetName=winuae -dTargetPath=C:\projects\winuae\src\od-win32\wix\bin\Release\winuae.msi -dwinuae.Configuration=Release -d"winuae.FullConfiguration=Release|Win32" -dwinuae.Platform=Win32 -dwinuae.ProjectDir=C:\projects\winuae\src\od-win32\winuae_msvc14\ -dwinuae.ProjectExt=.vcxproj -dwinuae.ProjectFileName=winuae_msvc.vcxproj -dwinuae.ProjectName=winuae_msvc -dwinuae.ProjectPath=C:\projects\winuae\src\od-win32\winuae_msvc14\winuae_msvc.vcxproj -dwinuae.TargetDir=d:\amiga\ -dwinuae.TargetExt=.exe -dwinuae.TargetFileName=winuae.exe -dwinuae.TargetName=winuae -dwinuae.TargetPath=d:\amiga\winuae.exe -out obj\Release\ -arch x86 -ext "C:\Program Files (x86)\WiX Toolset v3.11\bin\\WixUIExtension.dll" Product.wxs WixUI_FeatureTree_NL.wxs

"C:\Program Files (x86)\WiX Toolset v3.11\bin\Light.exe" -out C:\projects\winuae\src\od-win32\wix\bin\winuae.msi -pdbout C:\projects\winuae\src\od-win32\wix\bin\Release\winuae.wixpdb -cultures:null -ext "C:\Program Files (x86)\WiX Toolset v3.11\bin\\WixUIExtension.dll" -contentsfile obj\Release\wix.wixproj.BindContentsFileListnull.txt -outputsfile obj\Release\wix.wixproj.BindOutputsFileListnull.txt -builtoutputsfile obj\Release\wix.wixproj.BindBuiltOutputsFileListnull.txt -wixprojectfile C:\projects\winuae\src\od-win32\wix\wix.wixproj obj\Release\Product.wixobj obj\Release\WixUI_FeatureTree_NL.wixobj



"C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" -d"DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\\" -dSolutionDir=C:\projects\winuae\src\od-win32\winuae_msvc15\ -dSolutionExt=.sln -dSolutionFileName=winuae_msvc.sln -dSolutionName=winuae_msvc -dSolutionPath=C:\projects\winuae\src\od-win32\winuae_msvc15\winuae_msvc.sln -dConfiguration=Release -dOutDir=bin\Release\ -dPlatform=x64 -dProjectDir=C:\projects\winuae\src\od-win32\wix\ -dProjectExt=.wixproj -dProjectFileName=wix.wixproj -dProjectName=wix -dProjectPath=C:\projects\winuae\src\od-win32\wix\wix.wixproj -dTargetDir=C:\projects\winuae\src\od-win32\wix\bin\Release\ -dTargetExt=.msi -dTargetFileName=winuae.msi -dTargetName=winuae -dTargetPath=C:\projects\winuae\src\od-win32\wix\bin\Release\winuae.msi -dwinuae.Configuration=Release -d"winuae.FullConfiguration=Release|x64" -dwinuae.Platform=x64 -dwinuae.ProjectDir=C:\projects\winuae\src\od-win32\winuae_msvc14\ -dwinuae.ProjectExt=.vcxproj -dwinuae.ProjectFileName=winuae_msvc.vcxproj -dwinuae.ProjectName=winuae_msvc -dwinuae.ProjectPath=C:\projects\winuae\src\od-win32\winuae_msvc14\winuae_msvc.vcxproj -dwinuae.TargetDir=d:\amiga\ -dwinuae.TargetExt=.exe -dwinuae.TargetFileName=winuae64.exe -dwinuae.TargetName=winuae64 -dwinuae.TargetPath=d:\amiga\winuae64.exe -out obj\Release\ -arch x64 -ext "C:\Program Files (x86)\WiX Toolset v3.11\bin\\WixUIExtension.dll" Product.wxs WixUI_FeatureTree_NL.wxs

"C:\Program Files (x86)\WiX Toolset v3.11\bin\Light.exe" -out C:\projects\winuae\src\od-win32\wix\bin\winuae64.msi -pdbout C:\projects\winuae\src\od-win32\wix\bin\Release\winuae.wixpdb -cultures:null -ext "C:\Program Files (x86)\WiX Toolset v3.11\bin\\WixUIExtension.dll" -contentsfile obj\Release\wix.wixproj.BindContentsFileListnull.txt -outputsfile obj\Release\wix.wixproj.BindOutputsFileListnull.txt -builtoutputsfile obj\Release\wix.wixproj.BindBuiltOutputsFileListnull.txt -wixprojectfile C:\projects\winuae\src\od-win32\wix\wix.wixproj obj\Release\Product.wixobj obj\Release\WixUI_FeatureTree_NL.wixobj
