#!/usr/bin/env bash
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

WINUAE_SMOKE_LOG=${WINUAE_SMOKE_LOG:-/tmp/winuae_unix_p96_guest_draw_8bit_smoke.log}
WINUAE_P96_OPEN_SCREEN=${WINUAE_P96_OPEN_SCREEN:-640x480x8}
WINUAE_P96_EXPECT_DRAW_BLITS=${WINUAE_P96_EXPECT_DRAW_BLITS:-chunky}
WINUAE_UNIX_RTG_TRACE_BLITS=${WINUAE_UNIX_RTG_TRACE_BLITS:-1}
export WINUAE_SMOKE_LOG WINUAE_P96_OPEN_SCREEN WINUAE_P96_EXPECT_DRAW_BLITS WINUAE_UNIX_RTG_TRACE_BLITS

exec "$SCRIPT_DIR/unix-smoke-p96-guest.sh" "$@"
