//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by winuae.rc
//
#define VS_VERSION_INFO                 1
#define IDS_KICKSTART                   1
#define IDS_DISK                        2
#define IDS_DISPLAY                     3
#define IDC_HARDDRIVE_IMAGE             3
#define IDC_LISTDIALOG_CLEAR            3
#define IDS_HARDDISK                    4
#define IDS_FLOPPY                      5
#define IDS_ABOUT                       6
#define IDS_LOADSAVE                    7
#define IDS_AVIOUTPUT                   8
#define IDS_IOPORTS                     9
#define IDS_MISC1                       10
#define IDS_MEMORY                      11
#define IDS_CPU                         12
#define IDS_CHIPSET                     13
#define IDS_INPUT                       14
#define IDS_FILTER                      15
#define IDS_MISC2                       16
#define IDS_PATHS                       17
#define IDS_QUICKSTART                  18
#define IDS_FRONTEND                    19
#define IDS_CHIPSET2                    20
#define IDS_GAMEPORTS                   21
#define IDS_EXPANSION                   22
#define IDS_EXPANSION2                  23
#define IDS_BOARD                       24
#define IDC_PANELTREE                   50
#define IDD_PANEL                       51
#define IDC_PANEL_FRAME                 52
#define IDC_PANEL_FRAME_OUTER           53
#define IDC_RESETAMIGA                  54
#define IDC_QUITEMU                     55
#define IDC_RESTARTEMU                  56
#define IDC_ERRORLOG                    57
#define IDS_EXTTEXT                     100
#define IDS_EXTACTUAL                   101
#define IDS_SOUND                       102
#define IDS_CDROM                       103
#define IDS_FRAMERATE                   104
#define IDS_SECOND                      105
#define IDS_THIRD                       106
#define IDD_KICKSTART                   107
#define IDS_FOURTH                      107
#define IDD_DISPLAY                     108
#define IDS_FIFTH                       108
#define IDD_MEMORY                      109
#define IDS_SIXTH                       109
#define IDD_FLOPPY                      110
#define IDS_SEVENTH                     110
#define IDD_CPU                         111
#define IDS_EIGHTH                      111
#define IDD_ABOUT                       112
#define IDS_NINTH                       112
#define IDD_HARDDISK                    113
#define IDS_TENTH                       113
#define IDS_SELECTADF                   114
#define IDS_ADF                         115
#define IDS_CHOOSEBLANK                 116
#define IDS_SELECTHDF                   117
#define IDS_HDF                         118
#define IDS_SELECTUAE                   119
#define IDS_UAE                         120
#define IDS_SELECTROM                   121
#define IDD_SOUND                       122
#define IDS_ROM                         122
#define IDI_APPICON                     123
#define IDS_SELECTKEY                   123
#define IDI_CPU                         124
#define IDS_KEY                         124
#define IDI_ABOUT                       125
#define IDS_SELECTINFO                  125
#define IDS_NONE                        126
#define IDS_VOLUME                      127
#define IDI_HARDDISK                    128
#define IDS_PATH                        128
#define IDS_RW                          129
#define IDI_SOUND                       130
#define IDS_SECTORS                     130
#define IDS_SURFACES                    131
#define IDS_RESERVED                    132
#define IDS_BLOCKSIZE                   133
#define IDI_FLOPPY                      134
#define IDS_NAME                        134
#define IDD_LOADSAVE                    135
#define IDS_DESCRIPTION                 135
#define IDS_ONEINSTANCE                 136
#define IDI_IOPORTS                     137
#define IDS_INSTALLDIRECTX              137
#define IDD_IOPORTS                     138
#define IDS_REGKEYCREATEFAILED          138
#define IDS_COULDNOTLOADCONFIG          139
#define IDD_CONTRIBUTORS                140
#define IDS_NOHELP                      140
#define IDD_MISC1                       141
#define IDS_MUSTSELECTCONFIG            141
#define IDD_HARDFILE                    142
#define IDS_NOAGA                       142
#define IDD_FILESYS                     143
#define IDS_INVALIDCOMPORT              143
#define IDS_WSOCK2NEEDED                144
#define IDD_MISC2                       144
#define IDS_UNSUPPORTEDPIXELFORMAT      145
#define IDS_WAVEOUTOPENFAILURE          146
#define IDS_MUSTENTERNAME               147
#define IDS_MUSTSELECTCONFIGFORDELETE   148
#define IDS_DELETECONFIGCONFIRMATION    149
#define IDI_MISC1                       150
#define IDS_DELETECONFIGTITLE           150
#define IDC_MYHAND                      151
#define IDS_GFXCARDCHECK                151
#define IDS_GFXCARDTITLE                152
#define IDD_DEBUGGER                    152
#define IDD_SETINFO                     153
#define IDS_MUSTSELECTPATH              153
#define IDI_ICON1                       153
#define IDS_SETTINGSERROR               154
#define IDD_CHIPSET                     154
#define IDS_MUSTSELECTNAME              155
#define IDI_MOVE_UP                     155
#define IDD_CHIPSET2                    155
#define IDS_MUSTSELECTFILE              156
#define IDI_MOVE_DOWN                   156
#define IDS_FAILEDHARDFILECREATION      157
#define IDD_AVIOUTPUT                   157
#define IDS_CREATIONERROR               158
#define IDI_AVIOUTPUT                   158
#define IDS_ERRORTITLE                  159
#define IDS_SELECTFILESYSROOT           160
#define IDD_FILTER                      160
#define IDS_DEFAULTMIDIOUT              161
#define IDS_DEFAULTMIDIIN               162
#define IDS_CONTRIBUTORS1               163
#define IDD_HARDDRIVE                   163
#define IDS_CONTRIBUTORS2               164
#define IDS_INVALIDPRTPORT              165
#define IDS_SELECTUSS                   166
#define IDS_RESTOREUSS                  166
#define IDS_USS                         167
#define IDS_WRONGOSVERSION              168
#define IDR_DRIVE_STARTUP_A500_1        168
#define IDS_SELECTFLASH                 169
#define IDR_DRIVE_CLICK_A500_1          169
#define IDS_FLASH                       170
#define IDR_DRIVE_SPIN_A500_1           170
#define IDD_INPUT                       171
#define IDS_INPUTHOSTWIDGET             171
#define IDI_INPUT                       172
#define IDS_INPUTAMIGAEVENT             172
#define IDD_DISK                        172
#define IDS_INPUTAUTOFIRE               173
#define IDS_SAVEUSS                     174
#define IDS_MIDIOVERFLOW                175
#define IDS_HFDSIZE                     176
#define IDS_DEVICE                      177
#define IDS_BOOTPRI                     178
#define IDS_WRONGDXVERSION              179
#define IDI_MISC2                       180
#define IDS_FLOPPY_COMPATIBLE           180
#define IDR_DRIVE_SNATCH_A500_1         181
#define IDS_FLOPPY_TURBO                181
#define IDI_DISK                        182
#define IDR_DRIVE_SPINND_A500_1         182
#define IDS_YES                         182
#define IDS_NO                          183
#define IDD_PATHS                       184
#define IDS_PRI_ABOVENORMAL             184
#define IDI_CONFIGFILE                  185
#define IDD_QUICKSTART                  185
#define IDS_PRI_NORMAL                  185
#define IDM_SYSTRAY                     186
#define IDS_PRI_BELOWNORMAL             186
#define IDS_PRI_LOW                     187
#define IDI_FOLDER                      188
#define IDS_OLDRTGLIBRARY               188
#define IDI_DISPLAY                     190
#define IDS_DEFAULT_AF                  190
#define IDS_DEFAULT_WINUAE              191
#define IDI_ROOT                        192
#define IDS_INP                         192
#define IDS_RESTOREINP                  193
#define IDI_MEMORY                      194
#define IDS_SAVEINP                     194
#define IDS_SCREEN_WINDOWED             195
#define IDS_SCREEN_FULLSCREEN           196
#define IDS_SCREEN_FULLWINDOW           197
#define IDS_SCREEN_VSYNC                198
#define IDS_SCREEN_VSYNC_AUTOSWITCH     199
#define IDS_SOUND_MONO                  200
#define IDS_SOUND_MIXED                 201
#define IDI_QUICKSTART                  201
#define IDS_SOUND_STEREO                202
#define IDS_SOUND_INTERPOL_DISABLED     203
#define IDS_DISABLED                    203
#define IDS_SOUND_INTERPOL_RH           204
#define IDI_PATHS                       204
#define IDS_SOUND_INTERPOL_CRUX         205
#define IDS_SOUND_FILTER_OFF            206
#define IDS_SOUND_FILTER_EMULATED       207
#define IDS_SOUND_FILTER_EMULATED_E     208
#define IDS_INPUT_COMPATIBILITY         209
#define IDS_INPUT_GAMEPORTS             209
#define IDS_INPUT_CUSTOM                210
#define IDS_INPUT_COPY_DEFAULT          211
#define IDS_INPUT_COPY_CUSTOM           212
#define IDS_3D_NO_FILTER                213
#define IDS_3D_BILINEAR                 214
#define IDS_VSYNC_DEFAULT               215
#define IDS_DRIVESOUND_NONE             216
#define IDS_DRIVESOUND_DEFAULT_A500     217
#define IDS_AVIOUTPUT_NOCODEC           218
#define IDS_DISK_IMAGENAME              219
#define IDS_DISK_DRIVENAME              220
#define IDS_FLOPPYTYPE35DD              227
#define IDS_FLOPPYTYPE35HD              228
#define IDS_FLOPPYTYPE525SD             229
#define IDS_FLOPPYTYPEDISABLED          230
#define IDS_STMENUNOFLOPPY              231
#define IDS_TREEVIEW_HARDWARE           232
#define IDS_TREEVIEW_HOST               233
#define IDS_TREEVIEW_MISC               234
#define IDS_TREEVIEW_SETTINGS           235
#define IDS_WINUAETITLE_MMB             236
#define IDS_WINUAETITLE_NORMAL          237
#define IDS_STARTEMULATION              238
#define IDS_TREEVIEW_ABOUT              239
#define IDS_NOHARDDRIVES                240
#define IDS_DEFAULT_HOST                241
#define IDS_SOUND_4CHANNEL              242
#define IDS_HF_FS_CUSTOM                243
#define IDS_SELECTFS                    244
#define IDS_KEYJOY                      245
#define IDB_XARCADE                     246
#define IDS_STATEFILE_UNCOMPRESSED      246
#define IDS_STATEFILE_RAMDUMP           247
#define IDS_STATEFILE_WAVE              248
#define IDD_FRONTEND                    249
#define IDS_SOUND_SWAP_PAULA            249
#define IDS_SOUND_SWAP_AHI              250
#define IDD_PROGRESSBAR                 250
#define IDS_SOUND_SWAP_BOTH             251
#define IDD_STRINGBOX                   251
#define IDB_LCD160X43                   252
#define IDS_SOUND_FILTER_ON_AGA         252
#define IDS_SOUND_FILTER_ON             253
#define IDS_SOUND_FILTER_ON_A500        253
#define IDS_DRIVESOUND_PC_FLOPPY        254
#define IDS_FLOPPYTYPE35DDESCOM         255
#define IDS_SOUND_STEREO2               256
#define IDS_INPUT_CUSTOMEVENT           257
#define IDS_DEFAULT_NEWWINUAE           258
#define IDS_SOUND_CLONED51              259
#define IDS_SOUND_51                    260
#define IDS_AUTOMATIC                   261
#define IDI_GAMEPORTS                   262
#define IDS_ALL                         262
#define IDD_GAMEPORTS                   263
#define IDS_INPUTTOGGLE                 263
#define IDS_NETDISCONNECTED             264
#define IDS_QS_CD                       265
#define IDS_QS_CD_AUTO                  266
#define IDS_QS_CD_IMAGE                 267
#define IDS_REMAPTITLE                  268
#define IDS_FILTER_NOOVERLAYS           269
#define IDS_STMENUNOCD                  270
#define IDS_ON                          271
#define IDS_INPUTQUALIFIER              272
#define IDS_GENERIC                     273
#define IDS_AUTODETECT                  274
#define IDS_OFF                         275
#define IDS_DELETECONFIGDIRCONFIRMATION 276
#define IDS_DELETECONFIGDIRNOTEMPTY     277
#define IDS_NUMSG_NEEDEXT2              300
#define IDS_NUMSG_NOROMKEY              301
#define IDS_NUMSG_KSROMCRCERROR         302
#define IDS_NUMSG_KSROMREADERROR        303
#define IDS_NUMSG_NOEXTROM              304
#define IDS_NUMSG_MODRIP_NOTFOUND       305
#define IDS_NUMSG_MODRIP_FINISHED       306
#define IDS_NUMSG_MODRIP_SAVE           307
#define IDS_NUMSG_KS68020               308
#define IDS_NUMSG_ROMNEED               309
#define IDS_NUMSG_NOZLIB                310
#define IDS_NUMSG_STATEHD               311
#define IDS_NUMSG_NOCAPS                312
#define IDS_NUMSG_OLDCAPS               313
#define IDS_IMGCHK_BOOTBLOCKCRCERROR    314
#define IDS_IMGCHK_BOOTBLOCKNO          315
#define IDS_IMGCHK_DAMAGED              316
#define IDS_IMGCHK_KS2                  317
#define IDS_IMGCHK_KS3                  318
#define IDS_ROMSCANEND                  319
#define IDS_ROM_AVAILABLE               320
#define IDS_ROM_UNAVAILABLE             321
#define IDS_HARDDRIVESAFETYWARNING1     322
#define IDS_NUMSG_KS68EC020             323
#define IDS_ROMSCANNOROMS               324
#define IDS_NUMSG_KICKREP               325
#define IDS_NUMSG_KICKREPNO             326
#define IDS_NUMSG_NOROM                 327
#define IDS_HDCLONE_OK                  328
#define IDS_HDCLONE_FAIL                329
#define IDR_DBGACCEL                    330
#define IDS_NUMSG_KS68030               331
#define IDS_NUMSG_EXPROMNEED            332
#define IDS_HARDDRIVESAFETYWARNING2     333
#define IDM_DBGCONTEXTMENU              334
#define IDS_SB_FAVORITENAME             334
#define IDD_DBGMEMINPUT                 335
#define IDS_SB_CUSTOMEVENT              335
#define IDS_FLOPPYTYPE35DDPC            336
#define IDS_FLOPPYTYPE35HDPC            337
#define IDS_JOYMODE_DEFAULT             338
#define IDS_JOYMODE_MOUSE               339
#define IDS_JOYMODE_JOYSTICK            340
#define IDS_JOYMODE_JOYSTICKANALOG      341
#define IDS_JOYMODE_LIGHTPEN            342
#define IDS_JOYMODE_MOUSE_CDTV          343
#define IDS_JOYMODE_JOYSTICK_CD32       344
#define IDS_TABLET_BOTH_CURSORS         345
#define IDI_DISKIMAGE                   345
#define IDS_TABLET_NATIVE_CURSOR        346
#define IDS_TABLET_HOST_CURSOR          347
#define IDI_PORTS                       347
#define IDS_AUTOSCALE_DISABLED          348
#define IDS_AUTOSCALE_SCALING           349
#define IDI_FILE                        349
#define IDS_AUTOSCALE_RESIZE            350
#define IDS_PRINTER_ASCII               351
#define IDD_EXPANSION                   351
#define IDS_PRINTER_EPSON               352
#define IDS_PRINTER_EPSON9              352
#define IDS_PRINTER_POSTSCRIPT_DETECTION 353
#define IDI_EXPANSION                   353
#define IDS_PRINTER_POSTSCRIPT_EMULATION 354
#define IDD_INPUTMAP                    354
#define IDS_PRINTER_PASSTHROUGH         355
#define IDD_INFOBOX                     355
#define IDS_RES_LORES                   356
#define IDS_RES_HIRES                   357
#define IDS_RES_SUPERHIRES              358
#define IDS_PRINTER_EPSON48             359
#define IDS_SELECTCD                    360
#define IDS_CD                          361
#define IDS_BUFFER_SINGLE               362
#define IDS_BUFFER_DOUBLE               363
#define IDS_BUFFER_TRIPLE               364
#define IDS_AUTOSCALE_CENTER            365
#define IDS_AUTOSCALE_MAX               366
#define IDS_AUTOSCALE_TV                367
#define IDS_JOYMODE_GAMEPAD             368
#define IDS_AUTOSCALE_DEFAULT           369
#define IDS_AUTOSCALE_MANUAL            370
#define IDS_PORT_AUTOFIRE               371
#define IDS_PORT_AUTOFIRE_TOGGLE        372
#define IDS_PORT_AUTOFIRE_ALWAYS        373
#define IDS_PORT_AUTOFIRE_NO            374
#define IDS_AUTOSCALE_INTEGER           375
#define IDS_SCREEN_VSYNC2_AUTOSWITCH    376
#define IDS_SCREEN_VSYNC2               377
#define IDS_SCREEN_VSYNC_NONE           378
#define IDS_FILTEROVERLAYTYPE_MASKS     379
#define IDS_FILTEROVERLAYTYPE_OVERLAYS  380
#define IDS_AUTOSCALE_INTEGER_AUTOSCALE 381
#define IDS_WSTYLE_BORDERLESS           382
#define IDS_WSTYLE_MINIMAL              383
#define IDS_WSTYLE_STANDARD             384
#define IDS_WSTYLE_EXTENDED             385
#define IDD_LIST                        386
#define IDS_MISCLISTITEMS1              386
#define IDS_MISCLISTITEMS2              387
#define IDD_CDDRIVE                     387
#define IDS_MISCLISTITEMS3              388
#define IDD_DIALOG1                     388
#define IDD_TAPEDRIVE                   388
#define IDS_WHEELMOUSE                  389
#define IDS_JOYMODE_WHEELMOUSE          389
#define IDD_ERRORLOG                    389
#define IDS_NUMSG_KS68030PLUS           390
#define IDD_DISKINFO                    390
#define IDS_SELECTTAPE                  391
#define IDS_TAPE                        392
#define IDS_SCREEN_NATIVE               392
#define IDS_SCREEN_RTG                  393
#define IDS_DISPLAYMODE_NATIVE          394
#define IDS_CURRENT_CONFIGURATION       395
#define IDS_SELECT_MENU                 396
#define IDS_SCSI_EMULATION              397
#define IDS_SLIRP                       398
#define IDD_EXPANSION2                  398
#define IDS_SLIRP_INBOUND               399
#define IDD_BOARDS                      399
#define IDS_FILTER_PAL_EXTRA            400
#define IDD_CHSQUERY                    400
#define IDS_FILTER_3D_EXTRA             401
#define IDS_ALWAYS_ON                   402
#define IDS_DISPLAY_ATTRIBUTES          403
#define IDS_NUMSG_NO_PPC                404
#define IDS_NUMSG_UAEBOOTROM_PCC        405
#define IDS_AUTOSCALE_OVERSCAN_BLANK    408
#define IDS_NUMSG_NOMEMORY              410
#define IDS_EXPANSION_CATEGORY          411
#define IDS_WINUAETITLE_PAUSED          412
#define IDS_MOUSE_UNTRAP_MODE           413
#define IDS_TABLET_MODE                 414
#define IDC_HARDDRIVE_ID                415
#define IDS_MISCLISTITEMS4              416
#define IDS_SHUTDOWN_NOTIFICATION       417
#define IDS_QUIT_WARNING                418
#define IDS_UNMAPPED_ADDRESS            419
#define IDS_GENLOCK_OPTIONS             420
#define IDS_READONLYCONFIRMATION        421
#define IDS_SCREEN_NATIVELACE           422
#define IDS_PORT_AUTOFIRE_TOGGLENOAF    423
#define IDS_DEFAULT_WINUAECUSTOM        424
#define IDS_SYNCMODE_COMBINED           425
#define IDS_SYNCMODE_CSYNC              426
#define IDS_SYNCMODE_HVSYNC             427
#define IDS_MEMINFO                     428
#define IDS_INPUTINVERT                 429
#define IDS_BOARDTYPE                   430
#define IDS_BOARDNAME                   431
#define IDS_BOARDSTART                  432
#define IDS_BOARDEND                    433
#define IDS_BOARDSIZE                   434
#define IDS_BOARDID                     435
#define IDS_ASSOCIATEEXTENSION          436
#define IDS_GAMEPORTS_CUSTOM            437
#define IDS_CURRENT_HOST                439
#define IDS_NONE2                       440
#define IDS_SOUND_CLONED71              441
#define IDS_SOUND_71                    442
#define IDS_SOUND_FILTER_ON_FIXEDONLY   443
#define IDS_MISCLISTITEMS5              444
#define IDS_MISCLISTITEMS6              445
#define IDS_CHOOSE_AUDIO_CODEC          446
#define IDS_CHOOSE_VIDEO_CODEC          447
#define IDS_DISPLAY_OPTIMIZATION_FULL   448
#define IDS_DISPLAY_OPTIMIZATION_PARTIAL 449
#define IDS_DISPLAY_OPTIMIZATION_NONE   450
#define IDS_KEYBOARD_DISCONNECTED       451
#define IDS_KEYBOARD_HIGHLEVEL          452
#define IDS_QS_MODELS                   1000
#define IDS_QS_MODEL_A500               1001
#define IDS_QS_MODEL_A500P              1002
#define IDS_QS_MODEL_A600               1003
#define IDS_QS_MODEL_A1000              1004
#define IDS_QS_MODEL_A1200              1005
#define IDS_QS_MODEL_CD32               1006
#define IDS_QS_MODEL_CDTV               1007
#define IDS_QS_MODEL_UAE                1008
#define IDS_QS_MODEL_ARCADIA            1009
#define IDS_QS_MODEL_A3000              1010
#define IDS_QS_MODEL_A4000              1011
#define IDS_QS_MODEL_A4000T             1012
#define IDS_QS_MODEL_MACROSYSTEM        1013
#define IDS_QS_MODEL_ALG                1014
#define IDC_RESOLUTION                  1021
#define IDC_SERIAL                      1022
#define IDC_REFRESHRATE                 1022
#define IDC_ILLEGAL                     1023
#define IDC_MIDILIST                    1023
#define IDC_MIDIOUTLIST                 1023
#define IDC_DA_MODE                     1023
#define IDC_MIDIINLIST                  1024
#define IDC_RESOLUTION2                 1024
#define IDC_DISPLAYSELECT               1024
#define IDC_AUTOCONFIG                  1025
#define IDC_PRINTERLIST                 1025
#define IDC_CHIPMEM                     1026
#define IDC_CREATELOGFILE               1026
#define IDC_PORT0_JOYS                  1026
#define IDC_SCREENMODE_NATIVE           1026
#define IDC_PRINTERTYPELIST             1026
#define IDC_FASTMEM                     1027
#define IDC_PORT1_JOYS                  1027
#define IDC_SCREENMODE_RTG              1027
#define IDC_DONGLELIST                  1027
#define IDC_PORT_TABLET_CURSOR          1028
#define IDC_SAMPLERLIST                 1028
#define IDC_DISPLAY_BUFFERCNT           1028
#define IDC_MEMORYMEM                   1028
#define IDC_PORT0_JOYSMODE              1029
#define IDC_SCREENMODE_NATIVE2          1029
#define IDC_SLOWMEM                     1030
#define IDC_PORT1_JOYSMODE              1030
#define IDC_SCREENMODE_RTG2             1030
#define IDC_PORT2_JOYS                  1031
#define IDC_SCREENMODE_NATIVE3          1031
#define IDC_PORT3_JOYS                  1032
#define IDC_PARALLEL                    1033
#define IDC_PORT0_AF                    1033
#define IDC_PORT1_AF                    1034
#define IDC_MOUSE_UNTRAPMODE            1035
#define IDC_PORT_TABLET_MODE            1036
#define IDC_PORT0_JOYSSUB               1037
#define IDC_PORT1_JOYSSUB               1038
#define IDC_PORT2_JOYSSUB               1039
#define IDC_PORT3_JOYSSUB               1040
#define IDC_FOCUSMINIMIZE               1041
#define IDC_FASTTEXT                    1043
#define IDC_FASTRAM                     1044
#define IDC_CHIPRAM                     1045
#define IDC_SLOWRAM                     1046
#define IDC_Z3TEXT                      1047
#define IDC_Z3FASTRAM                   1048
#define IDC_Z3FASTMEM                   1049
#define IDC_MEMORYRAM                   1050
#define IDC_Z3CHIPMEM                   1052
#define IDC_Z3CHIPRAM                   1053
#define IDC_MAX32RAM                    1054
#define IDC_CPUBOARDRAM                 1055
#define IDC_UAEHOME                     1070
#define IDC_PICASSOHOME                 1071
#define IDC_AMIGAHOME                   1072
#define IDC_WINUAEHOME                  1073
#define IDC_AIABHOME                    1074
#define IDC_CLOANTOHOME                 1075
#define IDC_THEROOTS                    1076
#define IDC_CAPS                        1077
#define IDC_ABIME                       1078
#define IDC_AMIKIT                      1080
#define IDC_RICHEDIT1                   1091
#define IDC_RICHEDIT2                   1092
#define IDC_CONTRIBUTORS                1124
#define IDC_BLACKER_THAN_BLACK          1170
#define IDC_BLITIMM                     1174
#define IDC_BLITWAIT                    1175
#define IDC_LORES                       1176
#define IDC_KEYBOARDNKRO                1176
#define IDC_RATE2BOX                    1177
#define IDC_AUTORESOLUTIONSELECT        1178
#define IDC_LORES_SMOOTHED              1179
#define IDC_FLICKERFIXER                1180
#define IDC_PROGRAMMED_AUTO             1181
#define IDC_AUTORESOLUTIONVGA           1181
#define IDC_RATE2ENABLE                 1182
#define IDC_GRAYSCALE                   1183
#define IDC_OVERSCANMODE                1184
#define IDC_FRAMERATE                   1185
#define IDC_RESYNCBLANK                 1186
#define IDC_XSIZE                       1187
#define IDC_YSIZE                       1188
#define IDC_INPUTAUTOFIRERATE           1188
#define IDC_LM_NORMAL                   1189
#define IDC_INPUTSPEEDD                 1189
#define IDC_LM_DOUBLED                  1190
#define IDC_INPUTSPEEDA                 1190
#define IDC_GFXCARDTEXT                 1191
#define IDC_LM_SCANLINES                1191
#define IDC_INPUTSPEEDM                 1191
#define IDC_LM_PDOUBLED2                1192
#define IDC_LM_PDOUBLED3                1193
#define IDC_FRAMERATE2                  1194
#define IDC_RATE2TEXT                   1195
#define IDC_DA_TEXT                     1196
#define IDC_LM_INORMAL                  1197
#define IDC_LM_IDOUBLED                 1198
#define IDC_LM_IDOUBLED2                1199
#define IDC_LM_IDOUBLED3                1200
#define IDC_CPU0                        1200
#define IDC_CPU1                        1201
#define IDC_CPU2                        1202
#define IDC_CPU3                        1203
#define IDC_CPU4                        1204
#define IDC_CPU5                        1205
#define IDC_CS_HOST                     1209
#define IDC_CS_68000                    1210
#define IDC_CS_ADJUSTABLE               1211
#define IDC_COMPATIBLE                  1214
#define IDC_TRUST0                      1215
#define IDC_TRUST1                      1216
#define IDC_CACHE                       1218
#define IDC_CYCLEEXACT                  1219
#define IDC_CPUIDLE                     1220
#define IDC_GENLOCK                     1220
#define IDC_COMPATIBLE_FPU              1221
#define IDC_FASTERRTG                   1221
#define IDC_GENLOCK_ALPHA               1221
#define IDC_COMPATIBLE24                1222
#define IDC_GENLOCK_KEEP_ASPECT         1222
#define IDC_SPEED                       1223
#define IDC_FPU0                        1224
#define IDC_FPU1                        1225
#define IDC_FPU2                        1226
#define IDC_FPU3                        1227
#define IDC_FPU_UNIMPLEMENTED           1228
#define IDC_SOUNDSETTINGS               1229
#define IDC_CPU_UNIMPLEMENTED           1229
#define IDC_8BIT                        1230
#define IDC_CPU_PPC                     1230
#define IDC_16BIT                       1231
#define IDC_PPC_CPUIDLE                 1231
#define IDC_11KHZ                       1232
#define IDC_FPU_MODE                    1232
#define IDC_22KHZ                       1233
#define IDC_SPEED_x86                   1233
#define IDC_44KHZ                       1234
#define IDC_CPUDATACACHE                1234
#define IDC_48KHZ                       1235
#define IDC_FPU4                        1235
#define IDC_SOUNDSIZE                   1236
#define IDC_FREQUENCY                   1237
#define IDC_SOUND0                      1238
#define IDC_SOUND1                      1239
#define IDC_SOUND2                      1240
#define IDC_SOUNDSTYLE                  1242
#define IDC_SOUNDSTYLE0                 1243
#define IDC_STEREO                      1244
#define IDC_SOUNDSTYLE1                 1245
#define IDC_SOUNDINTERPOLATION          1248
#define IDC_INTERPOLATION0              1249
#define IDC_SOUNDVOLUMESELECT           1249
#define IDC_INTERPOLATION1              1250
#define IDC_INTERPOLATION2              1251
#define IDC_STEREOMODE                  1252
#define IDC_SOUNDINTERPOLATION2         1252
#define IDC_STEREOMODE0                 1253
#define IDC_STEREOMODE1                 1254
#define IDC_STEREOMODE2                 1255
#define IDC_SOUNDINTERPOLATION3         1256
#define IDC_DF0TEXT                     1270
#define IDC_DF1TEXT                     1271
#define IDC_DF2TEXT                     1272
#define IDC_DF3TEXT                     1273
#define IDC_EJECT0                      1274
#define IDC_EJECT1                      1275
#define IDC_EJECT2                      1276
#define IDC_EJECT3                      1277
#define IDC_DF0                         1278
#define IDC_DF1                         1279
#define IDC_DF2                         1280
#define IDC_DF3                         1281
#define IDC_CREATE                      1282
#define IDC_CREATE_RAW                  1283
#define IDC_SNAPSHOTNAME                1284
#define IDC_INFO0                       1284
#define IDC_SNAPSHOT                    1285
#define IDC_SAVEIMAGE0                  1285
#define IDC_DOSAVESTATE                 1286
#define IDC_SAVEIMAGE1                  1286
#define IDC_DOLOADSTATE                 1287
#define IDC_SAVEIMAGE2                  1287
#define IDC_PROWIZARD                   1288
#define IDC_SAVEIMAGE3                  1288
#define IDC_GUI_FONT                    1288
#define IDC_GUI_DEFAULT                 1289
#define IDC_INFO1                       1289
#define IDC_INFO2                       1290
#define IDC_OSD_FONT                    1290
#define IDC_INFO3                       1291
#define IDC_GUI_LVDEFAULT               1291
#define IDC_PORT0_JOYSC                 1302
#define IDC_PORT0_KBDA                  1303
#define IDC_PORT0_KBDB                  1304
#define IDC_PORT0_KBDC                  1305
#define IDC_PORT0_KBDD                  1306
#define IDC_PORT0_KBDE                  1307
#define IDC_PORT1_JOYSC                 1308
#define IDC_PORT1_KBDA                  1309
#define IDC_PORT1_KBDB                  1310
#define IDC_PORT1_KBDC                  1311
#define IDC_PORT1_KBDD                  1312
#define IDC_PORT1_KBDE                  1313
#define IDC_MIDIFRAME                   1314
#define IDC_SERPARFRAME                 1315
#define IDC_SERIALFRAME                 1316
#define IDC_EDIT                        1334
#define IDC_REMOVE                      1335
#define IDC_VOLUMELIST                  1336
#define IDC_UP                          1337
#define IDC_DOWN                        1338
#define IDC_NEW_FS                      1339
#define IDC_NEW_HF                      1340
#define IDC_NEW_HD                      1341
#define IDC_PORT0                       1342
#define IDC_NEW_FSARCH                  1342
#define IDC_PORT1                       1343
#define IDC_NEW_CD                      1344
#define IDC_NEW_CD2                     1345
#define IDC_NEW_TAPE                    1345
#define IDC_PATH_NAME                   1362
#define IDC_SELECTOR                    1363
#define IDC_VOLUME_NAME                 1364
#define IDC_HARDFILE_DEVICE             1364
#define IDC_SECTORS                     1365
#define IDC_VOLUME_DEVICE               1365
#define IDC_HEADS                       1366
#define IDC_RESERVED                    1367
#define IDC_BLOCKSIZE                   1368
#define IDC_HARDFILE_BOOTPRI            1369
#define IDC_SECTORS_TEXT                1370
#define IDC_SURFACES_TEXT               1371
#define IDC_RESERVED_TEXT               1372
#define IDC_CYLINDERS_TEXT              1373
#define IDC_BLOCKSIZE_TEXT              1374
#define ID_OK                           1375
#define IDC_HARDFILE_BOOTPRI_TEXT       1375
#define IDC_PATH_FILESYS                1376
#define IDC_HARDFILE_DIR_TEXT           1377
#define IDC_HARDFILE_DEVICE_TEXT        1378
#define IDC_HFRDB                       1380
#define IDC_RDB                         1380
#define IDC_HARDFILE_FILESYS_TEXT       1380
#define IDC_FS_AUTOBOOT                 1380
#define IDC_FILESYS_SELECTOR            1381
#define IDC_HDF_AUTOBOOT                1382
#define IDC_HDF_DONOTMOUNT              1383
#define IDC_HDF_DONOTMOUNT2             1384
#define IDC_HDF_ADDFSRES                1384
#define IDC_HDF_PHYSGEOMETRY            1385
#define IDC_ROMFILE                     1390
#define IDC_KEYFILE                     1391
#define IDC_SCSIROMSELECT               1391
#define IDC_KICKCHOOSER                 1392
#define IDC_KEYCHOOSER                  1393
#define IDC_SCSIROMSUBSELECT            1393
#define IDC_ROMFILE2                    1394
#define IDC_SCSIROMSELECTCAT            1394
#define IDC_ROMCHOOSER2                 1395
#define IDC_EXPANSIONBOARDITEMSELECTOR  1395
#define IDC_FLASHCHOOSER                1396
#define IDC_EXPANSIONBOARDSELECTOR      1396
#define IDC_FLASHFILE                   1397
#define IDC_ACCELERATORBOARDITEMSELECTOR 1397
#define IDC_CARTFILE                    1398
#define IDC_ACCELERATORBOARDSELECTOR    1398
#define IDC_CARTCHOOSER                 1399
#define IDC_SAVE                        1400
#define IDC_CPUBOARDROMSUBSELECT        1400
#define IDC_LOAD                        1401
#define IDC_RTCCHOOSER                  1401
#define IDC_SCSIROMCHOOSER              1402
#define IDC_FLASHCHOOSER2               1402
#define IDC_CUSTOMROMCHOOSER            1402
#define IDC_DELETE                      1403
#define IDC_CPUBOARDROMCHOOSER          1403
#define IDC_CONFIGLIST                  1404
#define IDC_SCSIROMSELECTNUM            1404
#define IDC_EDITNAME                    1405
#define IDC_SCSIROMID                   1405
#define IDC_EDITDESCRIPTION             1406
#define IDC_CONFIGSEARCH                1407
#define IDC_QUICKSAVE                   1408
#define IDC_QUICKLOAD                   1409
#define IDC_EXIT                        1410
#define IDC_EDITPATH                    1410
#define IDC_RTCFILE                     1411
#define IDC_SCSIROMFILE                 1412
#define IDC_SCSIROMFILE2                1413
#define IDC_CPUBOARDROMFILE             1414
#define IDC_HDF_RDB                     1500
#define IDC_HFSIZE                      1501
#define IDC_HF_SIZE                     1501
#define IDC_LINEMODE                    1502
#define IDC_CREATEHF                    1502
#define IDC_HF_CREATE                   1502
#define IDC_SOCKETS                     1503
#define IDC_HF_DOSTYPE                  1503
#define IDC_HDF_CONTROLLER              1504
#define IDC_HDF_CONTROLLER_UNIT         1505
#define IDC_HDF_CONTROLLER_TYPE         1506
#define IDC_MAPDRIVES                   1507
#define IDC_HDF_FEATURE_LEVEL           1507
#define IDC_CPUTEXT                     1508
#define IDC_MAPDRIVES_NET               1508
#define IDC_CACHETEXT                   1509
#define IDC_SWAP                        1509
#define IDC_MAPDRIVES_CD                1509
#define IDC_SELECTRESTEXT               1510
#define IDC_FLUSHPRINTER                1510
#define IDC_MAPDRIVES_REMOVABLE         1510
#define IDC_PORT0_TEST                  1510
#define IDC_CPUTEXT_x86                 1510
#define IDC_SCREENRESTEXT               1511
#define IDC_MAPDRIVES_AUTO              1511
#define IDC_CPUTEXT2                    1511
#define IDC_CPUIDLETEXT                 1511
#define IDC_WIDTHTEXT                   1512
#define IDC_WINDOWEDTEXT                1512
#define IDC_MAPDRIVES_LIMIT             1512
#define IDC_HEIGHTTEXT                  1513
#define IDC_CD_SPEED                    1513
#define IDC_SETTINGSTEXT                1514
#define IDC_REFRESHTEXT                 1515
#define IDC_SETTINGSTEXT2               1515
#define IDC_DISABLE1                    1516
#define IDC_DF1WP                       1516
#define IDC_QUICKSTART_COMPA            1516
#define IDC_REFRESH2TEXT                1516
#define IDC_DISABLE2                    1517
#define IDC_DF2WP                       1517
#define IDC_QUICKSTART_DF               1517
#define IDC_DISABLE3                    1518
#define IDC_XCENTER                     1518
#define IDC_DF3WP                       1518
#define IDC_DF1WP2                      1518
#define IDC_QUICKSTART_HOST             1518
#define IDC_YCENTER                     1519
#define IDC_DISABLE0                    1519
#define IDC_DF0WP                       1519
#define IDC_OCS                         1520
#define IDC_HDFLOPPY                    1520
#define IDC_SETTINGSTEXT3               1520
#define IDC_DISPLAY_VARSYNC             1520
#define IDC_ECS_AGNUS                   1521
#define IDC_DISPLAY_RESIZE              1521
#define IDC_ECS_DENISE                  1522
#define IDC_ECS                         1523
#define IDC_AGA                         1524
#define IDC_OCSA1000                    1525
#define IDC_OCSA1000NOEHB               1526
#define IDC_NOSPEED                     1526
#define IDC_NTSC                        1527
#define IDC_NOSOUND                     1528
#define IDC_INACTIVE_NOSOUND            1528
#define IDC_MIDI                        1529
#define IDC_NOSPEEDPAUSE                1529
#define IDC_INACTIVE_PAUSE              1529
#define IDC_KICKSHIFTER                 1530
#define IDC_MIDI2                       1530
#define IDC_HIGHPRIORITY                1530
#define IDC_MINIMIZED_NOSOUND           1530
#define IDC_MINIMIZED_PAUSE             1531
#define IDC_STATEREC_RECORD             1532
#define IDC_INACTIVE_NOJOY              1532
#define IDC_KBLED_USB                   1533
#define IDC_ACTIVE_PAUSE                1534
#define IDC_KBLED_USB2                  1534
#define IDC_ACTIVE_NOSOUND              1535
#define IDC_STATECLEAR                  1536
#define IDC_MINIMIZED_NOJOY             1537
#define IDC_ACTIVE_NOJOY                1538
#define IDC_ACTIVE_NOKEYBOARD           1539
#define IDC_SER_SHARED                  1553
#define IDC_GUI_RESIZE                  1553
#define IDC_SER_CTSRTS                  1554
#define IDC_GUI_FULLSCREEN              1554
#define IDC_SER_DIRECT                  1555
#define IDC_GUI_DARKMODE                1555
#define IDC_PSPRINTER                   1556
#define IDC_PSPRINTERDETECT             1557
#define IDC_UAESERIAL                   1558
#define IDC_VIEWINFO                    1568
#define IDC_SETINFO                     1569
#define IDC_FLOPPYSLIDER                1570
#define IDC_CONFIGSEARCHCLEAR           1570
#define IDC_FLOPPYSLIDERTEXT            1571
#define IDC_FLOPPYSPEED                 1572
#define IDC_FLOPPYSPD                   1572
#define IDC_GUILANGUAGE_LIST            1573
#define IDC_SOUNDBUFFERRAM              1574
#define IDC_SOUNDADJUST                 1575
#define IDC_SOUNDBUFFERTEXT             1576
#define IDC_SOUNDVOLUME                 1576
#define IDC_SOUNDBUFFERMEM              1577
#define IDC_HARDFLUSH                   1578
#define IDC_SOUNDADJUSTNUM              1578
#define IDC_SOUNDVOLUMEEXT              1578
#define IDC_CONSTJUMP                   1579
#define IDC_SOUNDDRIVEVOLUME            1579
#define IDC_JITFPU                      1580
#define IDC_SOUNDVOLUME2                1580
#define IDC_NOFLAGS                     1581
#define IDC_SOUNDDRIVEVOLUME2           1581
#define IDC_CS_CACHE_TEXT               1582
#define IDC_SOUNDVOLUMEEXT2             1582
#define IDC_JITCRASH                    1582
#define IDC_CS_CACHE_TEXT2              1583
#define IDC_SOUNDDRIVEVOLUMEX           1583
#define IDC_COLLISIONS                  1584
#define IDC_JITENABLE                   1584
#define IDC_SOUNDDRIVEVOLUMEX2          1584
#define IDC_DISASSEMBLY                 1585
#define IDC_MMUENABLEOFF                1586
#define IDC_MMUENABLEEC                 1587
#define IDC_MMUENABLE                   1588
#define IDC_COLLISION0                  1589
#define IDC_COLLISION1                  1590
#define IDC_AUDIOSYNC                   1590
#define IDC_COLLISION2                  1591
#define IDC_COLLISION3                  1592
#define IDC_SOUNDLAGSLIDER              1592
#define IDC_SOUNDLAGCAPTION             1594
#define IDC_FLOPPYTYPE                  1594
#define IDC_SYNCPARAMS                  1595
#define IDC_DF0TYPE                     1595
#define IDC_SOUNDLAGTEXT                1596
#define IDC_DF1TYPE                     1596
#define IDC_DF2TYPE                     1597
#define IDC_SOUNDSPEEDSLIDER            1598
#define IDC_DF3TYPE                     1598
#define IDC_SOUNDSPEEDTEXT              1599
#define IDC_SOUNDSPEEDCAPTION           1600
#define IDC_RTGMATCHDEPTH               1601
#define IDC_ROMFILE2TEXT                1602
#define IDC_ROMTEXT                     1603
#define IDC_KEYTEXT                     1604
#define IDC_CD32                        1605
#define IDC_AKIKOC2P                    1605
#define IDC_FLASHTEXT                   1605
#define IDC_SCSIDEVICE                  1606
#define IDC_FLASHTEXT2                  1606
#define IDC_INPUTTYPE                   1607
#define IDC_INPUTSELECTTEXT             1608
#define IDC_NOUAEFSDB                   1608
#define IDC_INPUTDEVICE                 1609
#define IDC_MAPROM                      1609
#define IDC_NORECYCLEBIN                1609
#define IDC_AVIOUTPUT_FILETEXT          1610
#define IDC_INPUTDEVICETEXT             1610
#define IDC_ALWAYSONTOP                 1610
#define IDC_SCSIROMFILEAUTOBOOT         1610
#define IDC_AVIOUTPUT_FILE              1611
#define IDC_INPUTLIST                   1611
#define IDC_CATWEASEL                   1611
#define IDC_INPUTAMIGA                  1612
#define IDC_SCSIROMSELECTED             1612
#define IDC_AVIOUTPUT_VIDEO             1613
#define IDC_INPUTAUTOFIRE               1613
#define IDC_EXPANSIONBOARDCHECKBOX      1613
#define IDC_AVIOUTPUT_AUDIO             1614
#define IDC_INPUTCOPYFROM               1614
#define IDC_SANA2                       1614
#define IDC_AVIOUTPUT_VIDEO_CODEC       1615
#define IDC_INPUTDEVICEDISABLE          1615
#define IDC_AVIOUTPUT_ACTIVATED         1615
#define IDC_AVIOUTPUT_AUDIO_CODEC       1616
#define IDC_INPUTAMIGACNT               1616
#define IDC_FILTERHZ                    1616
#define IDC_SAMPLERIPPER_ACTIVATED      1616
#define IDC_AVIOUTPUT_BORDER_TRIM       1617
#define IDC_FILTERVZ                    1617
#define IDC_ACCELERATORBOARDCHECKBOX    1617
#define IDC_AVIOUTPUT_AUDIO_STATIC      1618
#define IDC_FILTERHO                    1618
#define IDC_AVIOUTPUT_VIDEO_STATIC      1619
#define IDC_FILTERVO                    1619
#define IDC_AVIOUTPUT_8BIT              1620
#define IDC_FILTERASPECT                1620
#define IDC_STATEREC_PLAY               1620
#define IDC_AVIOUTPUT_24BIT             1621
#define IDC_FILTERASPECT2               1621
#define IDC_STATEREC_SAVE               1621
#define IDC_AVIOUTPUT_WIDTH             1622
#define IDC_AVIOUTPUT_HEIGHT            1623
#define IDC_AVIOUTPUT_FRAME             1624
#define IDC_FILTERXL                    1624
#define IDC_FILTERSLR                   1625
#define IDC_FILTERHZMULT                1626
#define IDC_FILTERMODE                  1627
#define IDC_FILTERFILTERH               1628
#define IDC_FILTERDEFAULT               1629
#define IDC_FILTERXTRA                  1630
#define IDC_INPUTDEADZONE               1630
#define IDC_INPUTCOPY                   1631
#define IDC_FILTERPRESETS               1631
#define IDC_SCREENSHOT                  1632
#define IDC_INPUTSWAP                   1632
#define IDC_FILTERPRESETLOAD            1632
#define IDC_FLOPPYSPDTEXT               1633
#define IDC_FILTERPRESETSAVE            1633
#define IDC_INPUTREMAP                  1633
#define IDC_FLOPPYSPD_TEXT              1634
#define IDC_FILTERPRESETDELETE          1634
#define IDC_INPUTTEST                   1634
#define IDC_HARDDRIVE                   1635
#define IDC_INACTIVE_PRI                1635
#define IDC_FILTERVZMULT                1635
#define IDC_INPUTTEST2                  1635
#define IDC_SOUNDPRIMARY                1636
#define IDC_MINIMIZED_PRI               1636
#define IDC_FILTERAUTOSCALE             1636
#define IDC_VOLUME_BOOTPRI_TEXT         1637
#define IDC_FILTEROVERLAY               1637
#define IDC_VOLUME_BOOTPRI              1638
#define IDC_FILTEROVERLAYTYPE           1638
#define IDC_KBLED1                      1639
#define IDC_FILTERFILTERV               1639
#define IDC_KBLED2                      1640
#define IDC_SOUNDFILTER                 1640
#define IDC_KBLED3                      1641
#define IDC_SOUNDCALIBRATE              1641
#define IDC_ACTIVE_PRIORITY             1642
#define IDC_SOUNDDRIVE                  1642
#define IDC_KBLED4                      1642
#define IDC_GUI_SIZE                    1642
#define IDC_INACTIVE_PRIORITY           1643
#define IDC_ACTIVE_PRI                  1644
#define IDC_MINIMIZED_PRIORITY          1645
#define IDC_AVIOUTPUT_FRAMELIMITER      1645
#define IDC_STATEREC_RATE               1646
#define IDC_SOUNDDRIVESELECT            1647
#define IDC_AVIOUTPUT_NOSOUNDOUTPUT     1647
#define IDC_STATE_BUFFERSIZE_TEXT       1648
#define IDC_CONFIGTREE                  1648
#define IDC_AVIOUTPUT_NOSOUNDSYNC       1648
#define IDC_AVIOUTPUT_OPTIONS           1649
#define IDC_STATE_RATE_TEXT             1649
#define IDC_DISKLISTREMOVE              1649
#define IDC_DF0QENABLE                  1649
#define IDC_AVIOUTPUT_ORIGINALSIZE      1649
#define IDC_SOUNDCARD                   1650
#define IDC_UPBM                        1650
#define IDC_DISKLISTINSERT              1650
#define IDC_DF1QENABLE                  1650
#define IDC_SCREENSHOT_ORIGINALSIZE     1650
#define IDC_SOUNDCARDLIST               1651
#define IDC_STATE_BUFFERSIZE2           1651
#define IDC_STATEREC_BUFFERSIZE         1651
#define IDC_DISKLISTREMOVEALL           1651
#define IDC_SOUNDFREQ                   1652
#define IDC_STATEREC_AUTOPLAY           1652
#define IDC_SOUNDFREQTXT                1653
#define IDC_SCREENSHOT_CLIP             1653
#define IDC_SOUNDFILTERTXT              1654
#define IDC_SCREENSHOT_PALETTED         1654
#define IDC_SOUNDSTEREO                 1655
#define IDC_CONFIGTYPE                  1655
#define IDC_SCREENSHOT_AUTO             1655
#define IDC_SOUNDDRIVETXT               1656
#define IDC_PATHS_ROM                   1656
#define IDC_SOUNDSTEREOSEP              1656
#define IDC_SOUNDSTEREOTXT              1657
#define IDC_PATHS_CONFIG                1657
#define IDC_SOUNDINTERPOLATIONTXT       1658
#define IDC_PATHS_SCREENSHOT            1658
#define IDC_DISK                        1659
#define IDC_DISKLIST                    1659
#define IDC_PATHS_SAVEIMAGE             1659
#define IDC_SOUNDSTEREOSEPTXT           1659
#define IDC_PATHS_SAVESTATE             1660
#define IDC_SOUNDSTEREOMIXTXT           1660
#define IDC_PATHS_ROMS                  1661
#define IDC_SOUNDSTEREOMIX              1661
#define IDC_PATHS_CONFIGS               1662
#define IDC_SOUNDSWAP                   1662
#define IDC_PATHS_SCREENSHOTS           1663
#define IDC_PATHS_SAVESTATES            1664
#define IDC_SOUNDSTEREOSWAPTXT          1664
#define IDC_SOUNDSWAPTXT                1664
#define IDC_PATHS_SAVEIMAGES            1665
#define IDC_PATHS_ROML                  1666
#define IDC_PATHS_CONFIGL               1667
#define IDC_PATHS_SCREENSHOTL           1668
#define IDC_PATHS_STATEFILEL            1669
#define IDC_PATHS_SAVEIMAGEL            1670
#define IDC_PATHS_DEFAULT               1671
#define IDC_ROM_RESCAN                  1672
#define IDC_QUICKSTARTMODE              1673
#define IDC_RESETREGISTRY               1673
#define IDC_QUICKSTART_MODEL            1674
#define IDC_PATHS_AVIOUTPUTL            1674
#define IDC_QUICKSTART_CONFIGURATION    1675
#define IDC_PATHS_AVIOUTPUT             1675
#define IDC_QUICKSTART_COMPATIBILITY    1676
#define IDC_PATHS_AVIOUTPUTS            1676
#define IDC_QUICKSTART_CONFIG           1677
#define IDC_RESETDISKHISTORY            1677
#define IDC_DF0Q                        1678
#define IDC_DF0QQ                       1678
#define IDC_PATHS_RIPSL                 1678
#define IDC_DF1Q                        1679
#define IDC_QUICKSTART_HOSTCONFIG       1679
#define IDC_PATHS_RIP                   1679
#define IDC_DF1QQ                       1680
#define IDC_PATHS_RIPS                  1680
#define IDC_QUICKSTART_SETCONFIG        1681
#define IDC_LOGOPEN                     1681
#define IDC_CONFIGAUTO                  1682
#define IDC_CD0Q_TYPE                   1682
#define IDC_PATHS_NVRAM                 1682
#define IDC_DF0TEXTQ                    1683
#define IDC_CONFIGNOLINK                1683
#define IDC_PATHS_NVRAMS                1683
#define IDC_DF0WPQ                      1684
#define IDC_LOGSAVE                     1684
#define IDC_EJECT0Q                     1685
#define IDC_PATHS_NVRAML                1685
#define IDC_DF1WPQ                      1686
#define IDC_PATHS_CUSTOMDATA            1686
#define IDC_EJECT1Q                     1687
#define IDC_DF1TEXTQ                    1688
#define IDC_INFO0Q                      1689
#define IDC_INFO1Q                      1690
#define IDC_FILTERXLV                   1692
#define IDC_FILTERVOV                   1693
#define IDC_FILTERHOV                   1694
#define IDC_CONFIGLINK                  1694
#define IDC_FILTERVZV                   1695
#define IDC_PS_PARAMS                   1695
#define IDC_CONFIGFOLDER                1695
#define IDC_FILTERHZV                   1696
#define IDC_HF_TYPE                     1696
#define IDC_PRINTERAUTOFLUSH            1697
#define IDC_PRINTERAUTOFLUSHTXT         1698
#define IDC_DISKTEXT                    1699
#define IDC_FE_LIST                     1700
#define IDC_FE_INFO                     1701
#define IDC_FE_INFO2                    1702
#define IDC_FE_SCREENSHOT               1702
#define IDC_PATHS_DEFAULTTYPE           1704
#define IDC_SCSIMODE                    1705
#define IDC_PROGRESSBAR                 1705
#define IDC_LOGSELECT                   1705
#define IDC_PROGRESSBAR_TEXT            1706
#define IDC_LANGUAGE                    1706
#define IDC_CREATE_NAME                 1707
#define IDC_SOUND_AUTO                  1709
#define IDC_FILTERKEEPASPECT            1709
#define IDC_CS_RTC                      1710
#define IDC_FILTERKEEPAUTOSCALEASPECT   1710
#define IDC_CS_CIAA_TOD1                1711
#define IDC_FILTERENABLE                1711
#define IDC_CS_CIAA_TOD2                1712
#define IDC_CS_EXT                      1712
#define IDC_CS_CIAA_TOD3                1713
#define IDC_SOUND_DS                    1713
#define IDC_MONITOREMU                  1713
#define IDC_CS_COMPATIBLE               1714
#define IDC_GENLOCKMODE                 1714
#define IDC_CS_RAMSEYREV                1715
#define IDC_SOUND_WASAPI                1715
#define IDC_GENLOCKMIX                  1715
#define IDC_CS_KSMIRROR_E0              1716
#define IDC_STRINGBOXEDIT               1716
#define IDC_SOUND_OPENAL                1716
#define IDC_MONITOREMU_MON              1716
#define IDC_CS_CD32CD                   1717
#define IDC_KEYBOARDMODE                1717
#define IDC_CS_CD32C2P                  1718
#define IDC_SOUND_PORTAUDIO             1718
#define IDC_DISPLAY_OPTIMIZATION        1718
#define IDC_CS_CD32NVRAM                1719
#define IDC_CS_CDTVCD                   1720
#define IDC_CS_CDTVRAM                  1721
#define IDC_CS_IDE1                     1722
#define IDC_CS_IDE2                     1723
#define IDC_CS_IDE3                     1724
#define IDC_CS_A1000RAM                 1724
#define IDC_CS_RAMSEY                   1725
#define IDC_CS_GARY                     1726
#define IDC_CS_FATGARY                  1726
#define IDC_CS_DMAC                     1727
#define IDC_CS_RTCADJUST                1728
#define IDC_CS_FATGARYREV               1729
#define IDC_CS_RTC1                     1731
#define IDC_CS_RTC2                     1732
#define IDC_CS_RTC3                     1733
#define IDC_CS_RTC4                     1734
#define IDC_CS_AGNUS                    1735
#define IDC_CS_AGNUSREV                 1736
#define IDC_CS_DENISE                   1737
#define IDC_CS_DENISEREV                1738
#define IDC_DBG_OUTPUT1                 1739
#define IDC_CS_PCMCIA                   1739
#define IDC_DBG_HELP                    1740
#define IDC_CS_AGNUSMODEL               1740
#define IDC_DBG_INPUT                   1741
#define IDC_CS_KSMIRROR_A8              1741
#define IDC_DBG_DREG                    1742
#define IDC_CS_CIAOVERLAY               1742
#define IDC_DBG_AREG                    1743
#define IDC_CS_RESETWARNING             1743
#define IDC_DBG_CCR                     1744
#define IDC_CS_AGNUSSIZE                1744
#define IDC_DBG_AMEM                    1745
#define IDC_DBG_SP_VBR                  1746
#define IDC_CS_CDTVCR                   1746
#define IDC_DBG_MMISC                   1747
#define IDC_CS_DENISEMODEL              1747
#define IDC_DBG_PC                      1748
#define IDC_DBG_PREFETCH                1749
#define IDC_DBG_FPREG                   1750
#define IDC_DBG_FPSR                    1751
#define IDC_DBG_OUTPUT2                 1752
#define IDC_CS_CIATODBUG                1752
#define IDC_DBG_MEMINPUT                1753
#define IDC_CS_Z3AUTOCONFIG             1753
#define IDC_DBG_MEMDOWN                 1754
#define IDC_CS_1MCHIPJUMPER             1754
#define IDC_DBG_MEMUP                   1755
#define IDC_CS_BYTECUSTOMWRITEBUG       1755
#define IDC_DBG_MEM                     1756
#define IDC_CS_COMPOSITECOLOR           1756
#define IDC_DBG_DASM                    1757
#define IDC_DBG_MEMDOWNFAST             1758
#define IDC_CS_TOSHIBAGARY              1758
#define IDC_DBG_MEMTOPC                 1759
#define IDC_CS_ROMISSLOW                1759
#define IDC_DBG_MEMUPFAST               1760
#define IDC_CS_CIA                      1760
#define IDC_DA_RESET                    1761
#define IDC_CS_MEMORYPATTERN            1761
#define IDC_DBG_STATUS                  1762
#define IDC_DBG_BRKPTS                  1763
#define IDC_DBG_MCUSTOM                 1764
#define IDC_DBG_MISC                    1765
#define IDC_DBG_CUSTOM                  1766
#define IDC_DBG_MISCCPU                 1767
#define IDC_CS_DMAC2                    1769
#define IDC_DF0ENABLE                   1773
#define IDC_DF1ENABLE                   1774
#define IDC_FS_SELECT_DIR               1774
#define IDC_FS_SELECT_FILE              1775
#define IDC_FLOPPY_FFS                  1775
#define IDC_DF2ENABLE                   1776
#define IDC_FS_SELECT_EJECT             1776
#define IDC_FS_RW                       1777
#define IDC_FLOPPY_BOOTABLE             1777
#define IDC_DF3ENABLE                   1778
#define IDC_HDF_RW                      1778
#define IDC_HDFINFO                     1779
#define IDC_DBG_AUTOSET                 1780
#define IDC_HF_SPARSE                   1780
#define IDC_HDF_LOCK                    1780
#define IDC_DBG_DASM2                   1781
#define IDC_HF_DYNAMIC                  1781
#define IDC_HDF_IDENTITY                1781
#define IDC_DBG_MEM2                    1782
#define IDC_HDFINFO2                    1782
#define IDC_DBG_MEMINPUT2               1783
#define IDC_HDFINFO3                    1783
#define IDC_DBG_ADDRINPUTTXT            1784
#define IDC_RTG_SCALE                   1785
#define IDC_RTG_8BIT                    1787
#define IDC_RTG_16BIT                   1788
#define IDC_PATHS_CONFIGCACHE           1788
#define IDC_RTG_24BIT                   1789
#define IDC_ASSOCIATELIST               1789
#define IDC_PORT_TABLET                 1789
#define IDC_PATHS_RELATIVE              1789
#define IDC_RTG_32BIT                   1790
#define IDC_ASSOCIATE_OFF               1790
#define IDC_CPU_MULTIPLIER              1790
#define IDC_CPU_FREQUENCY2              1790
#define IDC_LOGENABLE                   1790
#define IDC_DXMODE_OPTIONS              1791
#define IDC_RTG_SCALE_ALLOW             1791
#define IDC_CPU_FREQUENCY               1791
#define IDC_LOGENABLE2                  1791
#define IDC_PORT_TABLET_LIBRARY         1791
#define IDC_RTG_SCALE_ASPECTRATIO       1792
#define IDC_ASSOCIATE_ON                1792
#define IDC_DXMODE                      1792
#define IDC_REGISTRYMODE                1792
#define IDC_PORT_AUTOSWITCH             1792
#define IDC_RTG_VBLANKRATE              1793
#define IDC_DF0WPTEXTQ                  1793
#define IDC_WINDOWEDMODE                1793
#define IDC_PATHS_SAVEIMAGEORIGINALPATH 1793
#define IDC_DF1WPTEXTQ                  1794
#define IDC_RTG_Z2Z3                    1794
#define IDC_RTG_BUFFERCNT               1795
#define IDC_PATHS_RECURSIVEROMS         1795
#define IDC_RTG_VBINTERRUPT             1796
#define IDC_PATHS_ARTCACHE              1796
#define IDC_INPUTMAPLIST                1797
#define IDC_RTG_HWSPRITE                1797
#define IDC_PORT1_REMAP                 1798
#define IDC_RTG_CENTER                  1798
#define IDC_PORT0_REMAP                 1799
#define IDC_RTG_Z2Z4                    1799
#define IDC_RTG_NUM                     1799
#define IDC_PORT2_REMAP                 1800
#define IDC_RTG_THREAD                  1800
#define IDC_PORT3_REMAP                 1801
#define IDC_INPUTMAPOUT                 1801
#define IDC_RTG_INTEGERSCALE            1801
#define IDC_INFOBOX_TEXT2               1802
#define IDC_INPUTMAPOUTM                1802
#define IDC_RTG_SWITCHER                1802
#define IDC_INFOBOX_TEXT1               1803
#define IDC_INFOBOX_TEXT3               1804
#define IDC_CD_EJECT                    1804
#define IDC_CD_TEXT                     1805
#define IDC_CD_TYPE                     1806
#define IDC_CD_SELECT                   1807
#define IDC_RTG_DISPLAYSELECT           1809
#define IDC_FASTMEMAUTOCONFIGUSE        1809
#define IDC_MISCLIST                    1810
#define IDC_FASTMEMNOAUTOCONFIG         1810
#define IDC_STATENAME                   1811
#define IDC_FASTMEMDMA                  1811
#define IDC_SAMPLER_STEREO              1812
#define IDC_FASTMEMFORCE16              1812
#define IDC_LISTDIALOG_LIST             1813
#define IDC_FASTMEMSLOW                 1813
#define IDC_LOGPATH                     1814
#define IDC_MIDIROUTER                  1815
#define IDC_CDLIST                      1815
#define IDC_CS_IDE4                     1816
#define IDC_CS_DF0IDHW                  1817
#define IDC_FILTERSTACK                 1818
#define IDC_INPUTMAP_CAPTURE            1819
#define IDC_FILTERINTEGER               1819
#define IDC_INPUTMAP_CUSTOM             1820
#define IDC_INPUTMAP_DELETE             1821
#define IDC_INPUTMAP_TEST               1822
#define IDC_INPUTMAP_DELETEALL          1823
#define IDC_INPUTMAP_EXIT               1824
#define IDC_INPUTMAPADD                 1825
#define IDC_TAPELIST                    1826
#define IDC_INPUTMAP_SPECIALS           1826
#define IDC_NEW_TAPEPATH                1827
#define IDC_TAPEINFO                    1828
#define IDC_TAPE_PATH_NAME              1829
#define IDC_TAPE_SELECTOR               1830
#define IDC_NEW_TAPE_DIR                1831
#define IDC_TAPE_SELECT_DIR             1832
#define IDC_TAPE_SELECT_FILE            1833
#define IDC_TAPE_RW                     1834
#define IDC_ERRORLOGMESSAGE             1835
#define IDC_TAPE_SELECT_FILE2           1835
#define IDC_TAPE_EJECT                  1835
#define IDC_ERRORLOGCLEAR               1836
#define IDC_DISKINFOBOX                 1837
#define IDC_SAVEBOOTBLOCK               1838
#define IDC_P96RAM                      1839
#define IDC_FILTER_NATIVERTG            1839
#define IDC_P96MEM                      1840
#define IDC_DA_SLIDER                   1841
#define IDC_CPUBOARD_TYPE               1842
#define IDC_CPUBOARDMEM                 1843
#define IDC_Z3MAPPING                   1844
#define IDC_CPUBOARD_SUBTYPE            1845
#define IDC_MEMORYSELECT                1845
#define IDC_CYCLEEXACTMEMORY            1846
#define IDC_MEMORYBOARDSELECT           1846
#define IDC_UAEBOARD_TYPE               1848
#define IDC_AUTOCONFIG_MANUFACTURER     1849
#define IDC_AUTOCONFIG_PRODUCT          1850
#define IDC_BOARDLIST                   1850
#define IDC_AUTOCONFIG_DATA             1851
#define IDC_AUTOCONFIGCUSTOMSORT        1851
#define IDC_BOARDS_DOWN                 1852
#define IDC_RAM_ADDRESS                 1852
#define IDC_BOARDS_UP                   1853
#define IDC_RAM_ADDRESS2                1853
#define IDC_GENLOCKFILE                 1853
#define IDC_GENLOCKFILESELECT           1854
#define IDC_PATH_GEOMETRY               1855
#define IDC_PATH_GEOMETRY_SELECTOR      1856
#define IDC_EXPANSIONBOARDSTRINGBOX     1857
#define IDC_CS_UNMAPPED                 1858
#define IDC_CHS_CYLINDERS               1859
#define IDC_CS_HVCSYNC                  1859
#define IDC_CS_CIASYNC                  1859
#define IDC_CHS_HEADS                   1860
#define IDC_CONFIGCATEGORY              1860
#define IDC_CHS_SECTORS                 1861
#define IDC_CONFIGTAGS                  1861
#define IDC_CUSTOMROMSELECT             1861
#define IDC_ROM_ADDRESS                 1862
#define IDC_ROM_ADDRESS2                1863
#define IDC_CUSTOMROMFILE               1864
#define IDC_SCSIROMFILEPCMCIA           1865
#define IDC_KEYBOARD_SWAPHACK           1865
#define IDC_SCSIROM24BITDMA             1866
#define IDC_CUSTOMDATAPATH              1866
#define IDC_KEYBOARD_ENDHACK            1866
#define IDC_SER_RTSCTSDTRDTECD          1867
#define IDC_SER_RI                      1868
#define ID__FLOPPYDRIVES                40004
#define ID_FLOPPYDRIVES_DF0             40005
#define ID_ST_CONFIGURATION             40010
#define ID_ST_HELP                      40011
#define ID_ST_QUIT                      40012
#define ID_ST_EJECTALL                  40013
#define ID_ST_DF0                       40014
#define ID_ST_DF1                       40015
#define ID_ST_DF2                       40016
#define ID_ST_DF3                       40017
#define ID_ST_RESET                     40019
#define ID_DBG_PAGE1                    40020
#define ID_DBG_PAGE2                    40021
#define ID_DBG_PAGE3                    40022
#define ID_DBG_PAGE4                    40023
#define ID_DBG_PAGE5                    40024
#define ID_DBG_PAGE6                    40025
#define ID_DBG_PAGE7                    40026
#define ID_DBG_PAGE8                    40027
#define ID_DBG_PAGE9                    40028
#define ID_DBG_STEP_OVER                40029
#define ID_DBG_STEP_INTO                40030
#define ID_DBG_SETTOA0                  40031
#define ID_DBG_SETTOA1                  40032
#define ID_DBG_SETTOA2                  40033
#define ID_DBG_SETTOA3                  40034
#define ID_DBG_SETTOA4                  40035
#define ID_DBG_SETTOA5                  40036
#define ID_DBG_SETTOA6                  40037
#define ID_DBG_SETTOA7                  40038
#define ID_DBG_ENTERADDR                40039
#define ID_DBG_COPYLBLINE               40040
#define ID_DBG_COPYLB                   40041
#define ID_DBG_TOGGLEBP                 40042
#define ID_DBG_DELETEBPS                40043
#define ID_DBG_SETTOPC                  40044
#define ID_MENU_CDDRIVES                40045
#define ID_CDDRIVES_EJECT               40046
#define ID_ST_CDEJECTALL                40047
#define ID_CDDRIVES_CD                  40048
#define ID_ST_CD0                       40049
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        407
#define _APS_NEXT_COMMAND_VALUE         40050
#define _APS_NEXT_CONTROL_VALUE         1869
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
