//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by winuae.rc
//
#define IDS_KICKSTART                   1
#define IDS_DISK                        2
#define IDS_DISPLAY                     3
#define IDS_HARDDISK                    4
#define IDS_FLOPPY                      5
#define IDS_ABOUT                       6
#define IDS_LOADSAVE                    7
#define IDS_AVIOUTPUT                   8
#define IDS_PORTS                       9
#define IDS_MISC1                       10
#define IDS_MEMORY                      11
#define IDS_CPU                         12
#define IDS_CHIPSET                     13
#define IDS_INPUT                       14
#define IDS_OPENGL                      15
#define IDS_FILTER                      15
#define IDS_MISC2                       16
#define IDS_PATHS                       17
#define IDS_QUICKSTART                  18
#define IDS_EXTTEXT                     100
#define IDS_EXTACTUAL                   101
#define IDS_SOUND                       102
#define IDS_CDROM                       103
#define IDS_FRAMERATE                   104
#define IDS_SECOND                      105
#define IDS_THIRD                       106
#define IDD_KICKSTART                   107
#define IDS_FOURTH                      107
#define IDD_DISPLAY                     108
#define IDS_FIFTH                       108
#define IDD_MEMORY                      109
#define IDS_SIXTH                       109
#define IDD_FLOPPY                      110
#define IDS_SEVENTH                     110
#define IDD_CPU                         111
#define IDS_EIGHTH                      111
#define IDD_ABOUT                       112
#define IDS_NINTH                       112
#define IDD_HARDDISK                    113
#define IDS_TENTH                       113
#define IDS_SELECTADF                   114
#define IDS_ADF                         115
#define IDS_CHOOSEBLANK                 116
#define IDS_SELECTHDF                   117
#define IDS_HDF                         118
#define IDS_SELECTUAE                   119
#define IDS_UAE                         120
#define IDS_SELECTROM                   121
#define IDD_SOUND                       122
#define IDS_ROM                         122
#define IDI_APPICON                     123
#define IDS_SELECTKEY                   123
#define IDI_CPU                         124
#define IDS_KEY                         124
#define IDI_ABOUT                       125
#define IDS_SELECTINFO                  125
#define IDS_NONE                        126
#define IDS_VOLUME                      127
#define IDI_HARDDISK                    128
#define IDS_PATH                        128
#define IDS_RW                          129
#define IDI_SOUND                       130
#define IDS_SECTORS                     130
#define IDS_SURFACES                    131
#define IDS_RESERVED                    132
#define IDS_BLOCKSIZE                   133
#define IDI_FLOPPY                      134
#define IDS_NAME                        134
#define IDD_LOADSAVE                    135
#define IDS_DESCRIPTION                 135
#define IDS_ONEINSTANCE                 136
#define IDI_PORTS                       137
#define IDS_INSTALLDIRECTX              137
#define IDD_PORTS                       138
#define IDS_REGKEYCREATEFAILED          138
#define IDS_COULDNOTLOADCONFIG          139
#define IDD_CONTRIBUTORS                140
#define IDS_NOHELP                      140
#define IDD_MISC1                       141
#define IDS_MUSTSELECTCONFIG            141
#define IDD_HARDFILE                    142
#define IDS_NOAGA                       142
#define IDD_FILESYS                     143
#define IDS_INVALIDCOMPORT              143
#define IDS_WSOCK2NEEDED                144
#define IDD_MISC2                       144
#define IDS_UNSUPPORTEDPIXELFORMAT      145
#define IDS_WAVEOUTOPENFAILURE          146
#define IDS_MUSTENTERNAME               147
#define IDS_MUSTSELECTCONFIGFORDELETE   148
#define IDS_DELETECONFIGCONFIRMATION    149
#define IDI_MISC1                       150
#define IDS_DELETECONFIGTITLE           150
#define IDC_MYHAND                      151
#define IDS_GFXCARDCHECK                151
#define IDD_DIALOG1                     152
#define IDS_GFXCARDTITLE                152
#define IDD_DEBUGGER                    152
#define IDD_SETINFO                     153
#define IDS_MUSTSELECTPATH              153
#define IDI_ICON1                       153
#define IDS_SETTINGSERROR               154
#define IDD_CHIPSET                     154
#define IDS_MUSTSELECTNAME              155
#define IDI_MOVE_UP                     155
#define IDS_MUSTSELECTFILE              156
#define IDI_MOVE_DOWN                   156
#define IDS_FAILEDHARDFILECREATION      157
#define IDD_AVIOUTPUT                   157
#define IDS_CREATIONERROR               158
#define IDI_AVIOUTPUT                   158
#define IDS_ERRORTITLE                  159
#define IDS_SELECTFILESYSROOT           160
#define IDD_OPENGL                      160
#define IDD_FILTER                      160
#define IDS_DEFAULTMIDIOUT              161
#define IDS_DEFAULTMIDIIN               162
#define IDS_CONTRIBUTORS1               163
#define IDD_HARDDRIVE                   163
#define IDS_CONTRIBUTORS2               164
#define IDS_INVALIDPRTPORT              165
#define IDS_SELECTUSS                   166
#define IDS_RESTOREUSS                  166
#define IDS_USS                         167
#define IDS_WRONGOSVERSION              168
#define IDR_DRIVE_STARTUP_A500_1        168
#define IDS_SELECTFLASH                 169
#define IDR_DRIVE_CLICK_A500_1          169
#define IDS_FLASH                       170
#define IDR_DRIVE_SPIN_A500_1           170
#define IDD_INPUT                       171
#define IDS_INPUTHOSTWIDGET             171
#define IDI_INPUT                       172
#define IDS_INPUTAMIGAEVENT             172
#define IDD_DISK                        172
#define IDS_INPUTAUTOFIRE               173
#define IDS_SAVEUSS                     174
#define IDS_MIDIOVERFLOW                175
#define IDS_HFDSIZE                     176
#define IDS_DEVICE                      177
#define IDS_BOOTPRI                     178
#define IDS_WRONGDXVERSION              179
#define IDI_MISC2                       180
#define IDS_FLOPPY_COMPATIBLE           180
#define IDR_DRIVE_SNATCH_A500_1         181
#define IDS_FLOPPY_TURBO                181
#define IDI_DISK                        182
#define IDR_DRIVE_SPINND_A500_1         182
#define IDS_YES                         182
#define IDD_PANEL                       183
#define IDS_NO                          183
#define IDD_PATHS                       184
#define IDS_PRI_ABOVENORMAL             184
#define IDI_CONFIGFILE                  185
#define IDD_QUICKSTART                  185
#define IDS_PRI_NORMAL                  185
#define IDM_SYSTRAY                     186
#define IDS_PRI_BELOWNORMAL             186
#define IDS_PRI_LOW                     187
#define IDI_FOLDER                      188
#define IDI_DISPLAY                     190
#define IDI_ROOT                        192
#define IDI_ICON2                       194
#define IDI_MEMORY                      194
#define IDS_SOUND_MONO                  200
#define IDS_SOUND_MIXED                 201
#define IDI_QUICKSTART                  201
#define IDS_SOUND_STEREO                202
#define IDS_SOUND_INTERPOL_DISABLED     203
#define IDS_SOUND_INTERPOL_RH           204
#define IDI_PATHS                       204
#define IDS_SOUND_INTERPOL_CRUX         205
#define IDS_SOUND_FILTER_OFF            206
#define IDS_SOUND_FILTER_EMULATED       207
#define IDS_SOUND_FILTER_ON             208
#define IDS_INPUT_COMPATIBILITY         209
#define IDS_INPUT_CUSTOM                210
#define IDS_INPUT_COPY_DEFAULT          211
#define IDS_INPUT_COPY_CUSTOM           212
#define IDS_3D_NO_FILTER                213
#define IDS_3D_BILINEAR                 214
#define IDS_VSYNC_DEFAULT               215
#define IDS_DRIVESOUND_NONE             216
#define IDS_DRIVESOUND_DEFAULT_A500     217
#define IDS_AVIOUTPUT_NOCODEC           218
#define IDS_DISK_IMAGENAME              219
#define IDS_DISK_DRIVENAME              220
#define IDS_AGA8BIT                     221
#define IDS_UNSUPPORTEDSCREENMODE       222
#define IDS_UNSUPPORTEDSCREENMODE_1     223
#define IDS_UNSUPPORTEDSCREENMODE_2     224
#define IDS_UNSUPPORTEDSCREENMODE_3     225
#define IDS_UNSUPPORTEDSCREENMODE_4     226
#define IDS_FLOPPYTYPE35DD              227
#define IDS_FLOPPYTYPE35HD              228
#define IDS_FLOPPYTYPE525SD             229
#define IDS_FLOPPYTYPEDISABLED          230
#define IDS_STMENUNOFLOPPY              231
#define IDS_TREEVIEW_HARDWARE           232
#define IDS_TREEVIEW_HOST               233
#define IDS_TREEVIEW_MISC               234
#define IDS_TREEVIEW_SETTINGS           235
#define IDS_WINUAETITLE_MMB             236
#define IDS_WINUAETITLE_NORMAL          237
#define IDS_STARTEMULATION              238
#define IDS_TREEVIEW_ABOUT              239
#define IDS_NOHARDDRIVES                240
#define IDS_DEFAULT_HOST                241
#define IDS_SOUND_4CHANNEL              242
#define IDS_NUMSG_NEEDEXT2              300
#define IDS_NUMSG_NOROMKEY              301
#define IDS_NUMSG_KSROMCRCERROR         302
#define IDS_NUMSG_KSROMREADERROR        303
#define IDS_NUMSG_NOEXTROM              304
#define IDS_NUMSG_MODRIP_NOTFOUND       305
#define IDS_NUMSG_MODRIP_FINISHED       306
#define IDS_NUMSG_MODRIP_SAVE           307
#define IDS_NUMSG_KS68020               308
#define IDS_NUMSG_ROMNEED               309
#define IDS_NUMSG_NOZLIB                310
#define IDS_NUMSG_STATEHD               311
#define IDS_NUMSG_NOCAPS                312
#define IDS_NUMSG_OLDCAPS               313
#define IDS_IMGCHK_BOOTBLOCKCRCERROR    314
#define IDS_IMGCHK_BOOTBLOCKNO          315
#define IDS_IMGCHK_DAMAGED              316
#define IDS_IMGCHK_KS2                  317
#define IDS_IMGCHK_KS3                  318
#define IDS_ROMSCANEND                  319
#define IDS_ROM_AVAILABLE               320
#define IDS_ROM_UNAVAILABLE             321
#define IDS_HARDDRIVESAFETYWARNING      322
#define IDS_NUMSG_KS68EC020             323
#define IDS_ROMSCANNOROMS               324
#define IDS_NUMSG_KICKREP               325
#define IDS_NUMSG_KICKREPNO             326
#define IDS_NUMSG_NOROM                 327
#define IDS_QS_MODELS                   1000
#define IDS_QS_MODEL_A500               1001
#define IDS_QS_MODEL_A500P              1002
#define IDS_QS_MODEL_A600               1003
#define IDS_QS_MODEL_A1000              1004
#define IDS_QS_MODEL_A1200              1005
#define IDS_QS_MODEL_CD32               1006
#define IDS_QS_MODEL_CDTV               1007
#define IDS_QS_MODEL_UAE                1008
#define IDC_RESOLUTION                  1021
#define IDC_SERIAL                      1022
#define IDC_REFRESHRATE                 1022
#define IDC_ILLEGAL                     1023
#define IDC_MIDILIST                    1023
#define IDC_MIDIOUTLIST                 1023
#define IDC_DA_MODE                     1023
#define IDC_SHOWGUI                     1024
#define IDC_MIDIINLIST                  1024
#define IDC_RESOLUTION2                 1024
#define IDC_DISPLAYSELECT               1024
#define IDC_AUTOCONFIG                  1025
#define IDC_PRINTERLIST                 1025
#define IDC_CHIPMEM                     1026
#define IDC_CREATELOGFILE               1026
#define IDC_PORT0_JOYS                  1026
#define IDC_FASTMEM                     1027
#define IDC_SHOWLEDS                    1027
#define IDC_PORT1_JOYS                  1027
#define IDC_PRINTERLIST2                1028
#define IDC_SLOWMEM                     1030
#define IDC_PARALLEL                    1033
#define IDC_JULIAN                      1040
#define IDC_FASTTEXT                    1043
#define IDC_FASTRAM                     1044
#define IDC_CHIPRAM                     1045
#define IDC_SLOWRAM                     1046
#define IDC_Z3TEXT                      1047
#define IDC_Z3FASTRAM                   1048
#define IDC_Z3FASTMEM                   1049
#define IDC_UAEHOME                     1070
#define IDC_PICASSOHOME                 1071
#define IDC_AMIGAHOME                   1072
#define IDC_WINUAEHOME                  1073
#define IDC_AIABHOME                    1074
#define IDC_CLOANTOHOME                 1075
#define IDC_THEROOTS                    1076
#define IDC_CAPS                        1077
#define IDC_ABIME                       1078
#define IDC_RICHEDIT1                   1091
#define IDC_RICHEDIT2                   1092
#define IDC_CONTRIBUTORS                1124
#define IDC_ASPECT                      1170
#define IDC_BLIT32                      1173
#define IDC_BLITIMM                     1174
#define IDC_LORES                       1176
#define IDC_VSYNC                       1177
#define IDC_AFULLSCREEN                 1178
#define IDC_FRAMERATE                   1185
#define IDC_RATETEXT                    1186
#define IDC_XSIZE                       1187
#define IDC_YSIZE                       1188
#define IDC_INPUTAUTOFIRERATE           1188
#define IDC_LM_NORMAL                   1189
#define IDC_INPUTSPEEDD                 1189
#define IDC_LM_DOUBLED                  1190
#define IDC_INPUTSPEEDA                 1190
#define IDC_GFXCARDTEXT                 1191
#define IDC_LM_SCANLINES                1191
#define IDC_INPUTSPEEDM                 1191
#define IDC_P96RAM                      1192
#define IDC_PFULLSCREEN                 1192
#define IDC_P96MEM                      1193
#define IDC_DA_SLIDER                   1193
#define IDC_CPU0                        1200
#define IDC_CPU1                        1201
#define IDC_CPU2                        1202
#define IDC_CPU3                        1203
#define IDC_CPU4                        1204
#define IDC_CPU5                        1205
#define IDC_CPU6                        1206
#define IDC_SPEED                       1207
#define IDC_CS_HOST                     1209
#define IDC_CS_68000                    1210
#define IDC_CS_ADJUSTABLE               1211
#define IDC_CS_CPU_TEXT                 1212
#define IDC_CS_CHIPSET_TEXT             1213
#define IDC_COMPATIBLE                  1214
#define IDC_TRUST0                      1215
#define IDC_TRUST1                      1216
#define IDC_TRUST2                      1217
#define IDC_CACHE                       1218
#define IDC_CYCLEEXACT                  1219
#define IDC_CS_CPU_TEXT2                1219
#define IDC_CPUIDLE                     1220
#define IDC_SOUNDSETTINGS               1229
#define IDC_8BIT                        1230
#define IDC_16BIT                       1231
#define IDC_11KHZ                       1232
#define IDC_22KHZ                       1233
#define IDC_44KHZ                       1234
#define IDC_48KHZ                       1235
#define IDC_SOUNDSIZE                   1236
#define IDC_FREQUENCY                   1237
#define IDC_SOUND0                      1238
#define IDC_SOUND1                      1239
#define IDC_SOUND2                      1240
#define IDC_SOUND3                      1241
#define IDC_SOUNDSTYLE                  1242
#define IDC_SOUNDSTYLE0                 1243
#define IDC_STEREO                      1244
#define IDC_SOUNDSTYLE1                 1245
#define IDC_SOUNDINTERPOLATION          1248
#define IDC_INTERPOLATION0              1249
#define IDC_INTERPOLATION1              1250
#define IDC_INTERPOLATION2              1251
#define IDC_STEREOMODE                  1252
#define IDC_SOUNDINTERPOLATION2         1252
#define IDC_STEREOMODE0                 1253
#define IDC_STEREOMODE1                 1254
#define IDC_STEREOMODE2                 1255
#define IDC_SOUNDINTERPOLATION3         1256
#define IDC_DF0TEXT                     1270
#define IDC_DF1TEXT                     1271
#define IDC_DF2TEXT                     1272
#define IDC_DF3TEXT                     1273
#define IDC_EJECT0                      1274
#define IDC_EJECT1                      1275
#define IDC_EJECT2                      1276
#define IDC_EJECT3                      1277
#define IDC_DF0                         1278
#define IDC_DF1                         1279
#define IDC_DF2                         1280
#define IDC_DF3                         1281
#define IDC_CREATE                      1282
#define IDC_CREATE_RAW                  1283
#define IDC_SNAPSHOTNAME                1284
#define IDC_SNAPSHOT                    1285
#define IDC_SAVEIMAGE0                  1285
#define IDC_DOSAVESTATE                 1286
#define IDC_SAVEIMAGE1                  1286
#define IDC_DOLOADSTATE                 1287
#define IDC_SAVEIMAGE2                  1287
#define IDC_PROWIZARD                   1288
#define IDC_SAVEIMAGE3                  1288
#define IDC_PORT0_JOYSC                 1302
#define IDC_PORT0_KBDA                  1303
#define IDC_PORT0_KBDB                  1304
#define IDC_PORT0_KBDC                  1305
#define IDC_PORT1_JOYSC                 1308
#define IDC_PORT1_KBDA                  1309
#define IDC_PORT1_KBDB                  1310
#define IDC_PORT1_KBDC                  1311
#define IDC_PORT0                       1312
#define IDC_PORT1                       1313
#define IDC_MIDIFRAME                   1314
#define IDC_SERPARFRAME                 1315
#define IDC_SERIALFRAME                 1316
#define IDC_EDIT                        1334
#define IDC_REMOVE                      1335
#define IDC_VOLUMELIST                  1336
#define IDC_UP                          1337
#define IDC_DOWN                        1338
#define IDC_NEW_FS                      1339
#define IDC_NEW_HF                      1340
#define IDC_NEW_HD                      1341
#define IDC_PATH_NAME                   1362
#define IDC_SELECTOR                    1363
#define IDC_VOLUME_NAME                 1364
#define IDC_HARDFILE_DEVICE             1364
#define IDC_SECTORS                     1365
#define IDC_VOLUME_DEVICE               1365
#define IDC_HEADS                       1366
#define IDC_RESERVED                    1367
#define IDC_BLOCKSIZE                   1368
#define IDC_HARDFILE_BOOTPRI            1369
#define IDC_SECTORS_TEXT                1370
#define IDC_SURFACES_TEXT               1371
#define IDC_RESERVED_TEXT               1372
#define IDC_RESERVED_TEXT2              1373
#define IDC_BLOCKSIZE_TEXT              1374
#define ID_OK                           1375
#define IDC_HARDFILE_BOOTPRI_TEXT       1375
#define IDC_PATH_FILESYS                1376
#define IDC_HARDFILE_DIR_TEXT           1377
#define IDC_HARDFILE_DEVICE_TEXT        1378
#define IDC_RW                          1379
#define IDC_HFRDB                       1380
#define IDC_RW2                         1380
#define IDC_RDB                         1380
#define IDC_HARDFILE_FILESYS_TEXT       1380
#define IDC_FILESYS_SELECTOR            1381
#define IDC_ROMFILE                     1390
#define IDC_KEYFILE                     1391
#define IDC_KICKCHOOSER                 1392
#define IDC_KEYCHOOSER                  1393
#define IDC_ROMFILE2                    1394
#define IDC_ROMCHOOSER2                 1395
#define IDC_FLASHCHOOSER                1396
#define IDC_FLASHFILE                   1397
#define IDC_CARTFILE                    1398
#define IDC_CARTCHOOSER                 1399
#define IDC_SAVE                        1400
#define IDC_LOAD                        1401
#define IDC_DELETE                      1403
#define IDC_CONFIGLIST                  1404
#define IDC_EDITNAME                    1405
#define IDC_EDITDESCRIPTION             1406
#define IDC_QUICKSAVE                   1408
#define IDC_QUICKLOAD                   1409
#define IDC_EXIT                        1410
#define IDC_EDITPATH                    1410
#define IDC_HDF_RDB                     1500
#define IDC_HFSIZE                      1501
#define IDC_LINEMODE                    1502
#define IDC_CREATEHF                    1502
#define IDC_SOCKETS                     1503
#define IDC_RESETAMIGA                  1504
#define IDC_QUITEMU                     1505
#define IDC_TEST16BIT                   1506
#define IDC_MAPDRIVES                   1507
#define IDC_CPUTEXT                     1508
#define IDC_SWAP                        1509
#define IDC_CACHETEXT                   1509
#define IDC_SELECTRESTEXT               1510
#define IDC_FLUSHPRINTER                1510
#define IDC_SCREENRESTEXT               1511
#define IDC_WIDTHTEXT                   1512
#define IDC_WINDOWEDTEXT                1512
#define IDC_HEIGHTTEXT                  1513
#define IDC_SETTINGSTEXT                1514
#define IDC_REFRESHTEXT                 1515
#define IDC_SETTINGSTEXT2               1515
#define IDC_DISABLE1                    1516
#define IDC_DF1WP                       1516
#define IDC_QUICKSTART_COMPA            1516
#define IDC_DISABLE2                    1517
#define IDC_DF2WP                       1517
#define IDC_QUICKSTART_DF               1517
#define IDC_DISABLE3                    1518
#define IDC_XCENTER                     1518
#define IDC_DF3WP                       1518
#define IDC_DF1WP2                      1518
#define IDC_QUICKSTART_HOST             1518
#define IDC_YCENTER                     1519
#define IDC_DISABLE0                    1519
#define IDC_DF0WP                       1519
#define IDC_OCS                         1520
#define IDC_HDFLOPPY                    1520
#define IDC_ECS_AGNUS                   1521
#define IDC_ECS_DENISE                  1522
#define IDC_ECS                         1523
#define IDC_AGA                         1524
#define IDC_NTSC                        1525
#define IDC_NOSPEED                     1527
#define IDC_NOSOUND                     1528
#define IDC_INACTIVE_NOSOUND            1528
#define IDC_MIDI                        1529
#define IDC_NOSPEEDPAUSE                1529
#define IDC_INACTIVE_PAUSE              1529
#define IDC_KICKSHIFTER                 1530
#define IDC_MIDI2                       1530
#define IDC_HIGHPRIORITY                1530
#define IDC_MINIMIZED_NOSOUND           1530
#define IDC_MINIMIZED_PAUSE             1531
#define IDC_D0                          1532
#define IDC_STATE_CAPTURE               1532
#define IDC_D1                          1533
#define IDC_D2                          1534
#define IDC_D3                          1535
#define IDC_D4                          1536
#define IDC_D5                          1537
#define IDC_D6                          1538
#define IDC_D7                          1539
#define IDC_A0                          1540
#define IDC_A1                          1541
#define IDC_A2                          1542
#define IDC_A3                          1543
#define IDC_A4                          1544
#define IDC_A5                          1545
#define IDC_A6                          1546
#define IDC_A7                          1547
#define IDC_USP                         1548
#define IDC_SSP                         1549
#define IDC_PC                          1550
#define IDC_T1                          1551
#define IDC_T2                          1552
#define IDC_T3                          1553
#define IDC_SHARED                      1553
#define IDC_T4                          1554
#define IDC_SER_CTSRTS                  1554
#define IDC_T5                          1555
#define IDC_SERIAL_DIRECT               1555
#define IDC_T6                          1556
#define IDC_PSPRINTER                   1556
#define IDC_T7                          1557
#define IDC_PSPRINTERDETECT             1557
#define IDC_T8                          1558
#define IDC_T9                          1559
#define IDC_T10                         1560
#define IDC_T11                         1561
#define IDC_T12                         1562
#define IDC_T13                         1563
#define IDC_T14                         1564
#define IDC_T15                         1565
#define IDC_T16                         1566
#define IDC_VIEWINFO                    1568
#define IDC_SETINFO                     1569
#define IDC_FLOPPYSLIDER                1570
#define IDC_FLOPPYSLIDERTEXT            1571
#define IDC_FLOPPYSPEED                 1572
#define IDC_FLOPPYSPD                   1572
#define IDC_GUILANGUAGE_LIST            1573
#define IDC_SOUNDBUFFERRAM              1574
#define IDC_SOUNDADJUST                 1575
#define IDC_SOUNDBUFFERTEXT             1576
#define IDC_SOUNDVOLUME                 1576
#define IDC_SOUNDBUFFERMEM              1577
#define IDC_HARDFLUSH                   1578
#define IDC_SOUNDADJUSTNUM              1578
#define IDC_CONSTJUMP                   1579
#define IDC_SOUNDDRIVEVOLUME            1579
#define IDC_JITFPU                      1580
#define IDC_SOUNDVOLUME2                1580
#define IDC_NOFLAGS                     1581
#define IDC_SOUNDDRIVEVOLUME2           1581
#define IDC_CS_CACHE_TEXT               1582
#define IDC_FORCE                       1583
#define IDC_COLLISIONS                  1584
#define IDC_JITENABLE                   1584
#define IDC_DISASSEMBLY                 1585
#define IDC_CTRLF11                     1586
#define IDC_FASTCOPPER                  1588
#define IDC_COLLISION0                  1589
#define IDC_COLLISION1                  1590
#define IDC_AUDIOSYNC                   1590
#define IDC_COLLISION2                  1591
#define IDC_COLLISION3                  1592
#define IDC_SOUNDLAGSLIDER              1592
#define IDC_SOUNDLAGCAPTION             1594
#define IDC_FLOPPYTYPE                  1594
#define IDC_SYNCPARAMS                  1595
#define IDC_DF0TYPE                     1595
#define IDC_SOUNDLAGTEXT                1596
#define IDC_DF1TYPE                     1596
#define IDC_DF2TYPE                     1597
#define IDC_SOUNDSPEEDSLIDER            1598
#define IDC_DF0TYPE4                    1598
#define IDC_DF3TYPE                     1598
#define IDC_SOUNDSPEEDTEXT              1599
#define IDC_SOUNDSPEEDCAPTION           1600
#define IDC_NOOVERLAY                   1601
#define IDC_ROMFILE2TEXT                1602
#define IDC_ROMTEXT                     1603
#define IDC_KEYTEXT                     1604
#define IDC_CD32                        1605
#define IDC_AKIKOC2P                    1605
#define IDC_FLASHTEXT                   1605
#define IDC_SCSIDEVICE                  1606
#define IDC_FLASHTEXT2                  1606
#define IDC_AVIOUTPUT_PAL               1607
#define IDC_ASPI                        1607
#define IDC_INPUTTYPE                   1607
#define IDC_AVIOUTPUT_NTSC              1608
#define IDC_INPUTSELECTTEXT             1608
#define IDC_NOUAEFSDB                   1608
#define IDC_NOTASKBARBUTTON             1608
#define IDC_CLOCKSYNC                   1609
#define IDC_AVIOUTPUT_FPS               1609
#define IDC_INPUTDEVICE                 1609
#define IDC_MAPROM                      1609
#define IDC_AVIOUTPUT_FILETEXT          1610
#define IDC_INPUTDEVICETEXT             1610
#define IDC_AVIOUTPUT_FILE              1611
#define IDC_INPUTLIST                   1611
#define IDC_AVIOUTPUT_FPS_STATIC        1612
#define IDC_INPUTAMIGA                  1612
#define IDC_AVIOUTPUT_VIDEO             1613
#define IDC_INPUTAUTOFIRE               1613
#define IDC_AVIOUTPUT_AUDIO             1614
#define IDC_INPUTCOPYFROM               1614
#define IDC_AVIOUTPUT_VIDEO_CODEC       1615
#define IDC_OPENGLENABLE                1615
#define IDC_INPUTDEVICEDISABLE          1615
#define IDC_AVIOUTPUT_ACTIVATED         1615
#define IDC_FILTERENABLE                1615
#define IDC_AVIOUTPUT_AUDIO_CODEC       1616
#define IDC_OPENGLHZ                    1616
#define IDC_INPUTAMIGACNT               1616
#define IDC_FILTERHZ                    1616
#define IDC_AVIOUTPUT_BORDER_TRIM       1617
#define IDC_OPENGLVZ                    1617
#define IDC_FILTERVZ                    1617
#define IDC_AVIOUTPUT_AUDIO_STATIC      1618
#define IDC_OPENGLHO                    1618
#define IDC_FILTERHO                    1618
#define IDC_AVIOUTPUT_VIDEO_STATIC      1619
#define IDC_OPENGLVO                    1619
#define IDC_FILTERVO                    1619
#define IDC_AVIOUTPUT_8BIT              1620
#define IDC_OPENGLHZV                   1620
#define IDC_AVIOUTPUT_24BIT             1621
#define IDC_OPENGLVZV                   1621
#define IDC_AVIOUTPUT_WIDTH             1622
#define IDC_OPENGLHOV                   1622
#define IDC_AVIOUTPUT_HEIGHT            1623
#define IDC_OPENGLVOV                   1623
#define IDC_AVIOUTPUT_FRAME             1624
#define IDC_OPENGLSL                    1624
#define IDC_FILTERSL                    1624
#define IDC_OPENGLSLR                   1625
#define IDC_FILTERSLR                   1625
#define IDC_OPENGLSLV                   1626
#define IDC_OPENGLBITS                  1627
#define IDC_OPENGLMODE                  1627
#define IDC_FILTERMODE                  1627
#define IDC_OPENGLFILTER                1628
#define IDC_FILTERFILTER                1628
#define IDC_OPENGLDEFAULT               1629
#define IDC_FILTERDEFAULT               1629
#define IDC_INPUTDEADZONE               1630
#define IDC_OPENGLSL2                   1630
#define IDC_FILTERSL2                   1630
#define IDC_INPUTCOPY                   1631
#define IDC_OPENGLSL2V                  1631
#define IDC_FILTERPRESETS               1631
#define IDC_SCREENSHOT                  1632
#define IDC_INPUTSWAP                   1632
#define IDC_FILTERPRESETLOAD            1632
#define IDC_FLOPPYSPDTEXT               1633
#define IDC_FILTERPRESETSAVE            1633
#define IDC_FLOPPYSPD_TEXT              1634
#define IDC_FILTERPRESETDELETE          1634
#define IDC_KAILLERA                    1635
#define IDC_HARDDRIVE                   1635
#define IDC_INACTIVE_PRI                1635
#define IDC_KAILLERA_CHAT               1636
#define IDC_SOUNDPRIMARY                1636
#define IDC_MINIMIZED_PRI               1636
#define IDC_KAILLERA_CHAT_TEXT          1637
#define IDC_VOLUME_BOOTPRI_TEXT         1637
#define IDC_KAILLERA_CHAT_SEND          1638
#define IDC_VOLUME_BOOTPRI              1638
#define IDC_KAILLERA_LIST               1639
#define IDC_KBLED1                      1639
#define IDC_KAILLERAFELLOW              1640
#define IDC_KBLED2                      1640
#define IDC_SOUNDFILTER                 1640
#define IDC_KAILLERAJOY                 1641
#define IDC_KBLED3                      1641
#define IDC_SOUNDCALIBRATE              1641
#define IDC_KAILLERAJOYKEYBOARD         1642
#define IDC_ACTIVEPRIORITY              1642
#define IDC_ACTIVE_PRIORITY             1642
#define IDC_SOUNDDRIVE                  1642
#define IDC_KAILLERAOPTIONS             1643
#define IDC_INACTIVE_PRIORITY           1643
#define IDC_KAILLERASUPPRESSWARNINGS    1644
#define IDC_ACTIVE_PRI                  1644
#define IDC_KAILLERANONE                1645
#define IDC_MINIMIZED_PRIORITY          1645
#define IDC_AVIOUTPUT_FRAMELIMITER      1645
#define IDC_KAILLERACONTROLS            1646
#define IDC_STATE_RATE                  1646
#define IDC_KAILLERANOFPSLIMIT          1647
#define IDC_STATE_BUFFERSIZE            1647
#define IDC_SOUNDDRIVESELECT            1647
#define IDC_PANELTREE                   1647
#define IDC_AVIOUTPUT_DIMENSIONS_STATIC 1648
#define IDC_STATE_BUFFERSIZE_TEXT       1648
#define IDC_CONFIGTREE                  1648
#define IDC_AVIOUTPUT_OPTIONS           1649
#define IDC_STATE_RATE_TEXT             1649
#define IDC_DISKLISTREMOVE              1649
#define IDC_SOUNDCARD                   1650
#define IDC_CS_SOUND0                   1650
#define IDC_UPBM                        1650
#define IDC_SOUNDCARDLIST               1651
#define IDC_CS_SOUND1                   1651
#define IDC_SOUNDFREQ                   1652
#define IDC_CS_SOUND2                   1652
#define IDC_SOUNDCARD2                  1653
#define IDC_SOUNDFREQTXT                1653
#define IDC_PANEL_FRAME                 1653
#define IDC_SOUNDFILTERTXT              1654
#define IDC_PANEL_FRAME_OUTER           1654
#define IDC_SOUNDSTEREO                 1655
#define IDC_CONFIGTYPE                  1655
#define IDC_SOUNDDRIVETXT               1656
#define IDC_PATHS_ROM                   1656
#define IDC_SOUNDSTEREOSEP              1656
#define IDC_SOUNDSTEREOTXT              1657
#define IDC_PATHS_CONFIG                1657
#define IDC_SOUNDINTERPOLATIONTXT       1658
#define IDC_PATHS_SCREENSHOT            1658
#define IDC_DISK                        1659
#define IDC_DISKLIST                    1659
#define IDC_PATHS_SAVEIMAGE             1659
#define IDC_SOUNDSTEREOSEPTXT           1659
#define IDC_PATHS_SAVESTATE             1660
#define IDC_SOUNDSTEREOMIXTXT           1660
#define IDC_PATHS_ROMS                  1661
#define IDC_SOUNDSTEREOMIX              1661
#define IDC_PATHS_CONFIGS               1662
#define IDC_PATHS_SCREENSHOTS           1663
#define IDC_PATHS_SAVESTATES            1664
#define IDC_PATHS_SAVEIMAGES            1665
#define IDC_PATHS_ROML                  1666
#define IDC_PATHS_CONFIGL               1667
#define IDC_PATHS_SCREENSHOTL           1668
#define IDC_PATHS_STATEFILEL            1669
#define IDC_PATHS_SAVEIMAGEL            1670
#define IDC_PATHS_DEFAULT               1671
#define IDC_ROM_RESCAN                  1672
#define IDC_QUICKSTARTMODE              1673
#define IDC_RESETREGISTRY               1673
#define IDC_QUICKSTART_MODEL            1674
#define IDC_PATHS_AVIOUTPUTL            1674
#define IDC_QUICKSTART_CONFIGURATION    1675
#define IDC_PATHS_AVIOUTPUT             1675
#define IDC_QUICKSTART_COMPATIBILITY    1676
#define IDC_PATHS_AVIOUTPUTS            1676
#define IDC_QUICKSTART_CONFIG           1677
#define IDC_DF0Q                        1678
#define IDC_DF0QQ                       1678
#define IDC_DF1Q                        1679
#define IDC_QUICKSTART_HOSTCONFIG       1679
#define IDC_DF1QQ                       1680
#define IDC_QUICKSTART_SETCONFIG        1681
#define IDC_CONFIGAUTO                  1682
#define IDC_DF0TEXTQ                    1683
#define IDC_CONFIGNOLINK                1683
#define IDC_DF0WPQ                      1684
#define IDC_EJECT0Q                     1685
#define IDC_DF1WPQ                      1686
#define IDC_EJECT1Q                     1687
#define IDC_DF1TEXTQ                    1688
#define IDC_FILTERSL2V                  1691
#define IDC_FILTERSLV                   1692
#define IDC_FILTERVOV                   1693
#define IDC_FILTERHOV                   1694
#define IDC_CONFIGLINK                  1694
#define IDC_FILTERVZV                   1695
#define IDC_PS_PARAMS                   1695
#define IDC_FILTERHZV                   1696
#define ID__FLOPPYDRIVES                40004
#define ID_FLOPPYDRIVES_DF0             40005
#define ID_ST_CONFIGURATION             40010
#define ID_ST_HELP                      40011
#define ID_ST_QUIT                      40012
#define ID_ST_EJECTALL                  40013
#define ID_ST_DF0                       40014
#define ID_ST_DF1                       40015
#define ID_ST_DF2                       40016
#define ID_ST_DF3                       40017
#define ID_ST_RESET                     40019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        245
#define _APS_NEXT_COMMAND_VALUE         40021
#define _APS_NEXT_CONTROL_VALUE         1696
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
